"""``freeports-dev ci-check``: the one place that decides whether a commit goes through.

It reads what the measurements left in ``reports/``, the minima in ``ci.yaml`` and the class of the
branch, prints one table, and chooses an exit status. It measures nothing itself, which is the
point: when a commit is refused, the number that refused it is sitting in a file, written by a
command the person can re-run by hand. A gate whose figures cannot be reproduced is a gate that
gets switched off the first time it is wrong.

Five verdicts, and the two that are easy to get wrong are the reason this module exists:

======================  =========================================  ======  =========
verdict                 meaning                                    dev     prod
======================  =========================================  ======  =========
``pass``                measured, at or above the minimum          --      --
``below``               measured, under the minimum                notify  refuse
``unmeasured``          the tool is missing, or the run failed     notify  **refuse**
``stale``               measured at a commit other than HEAD       notify  **refuse**
``no threshold``        nothing configured for it                  listed  listed
======================  =========================================  ======  =========

**``unmeasured`` is never a pass.** A figure nobody could compute is not a figure above the
threshold, and reporting it as one is exactly the failure this project already ruled out for a
methodology page it could not reach: unverifiable is not granted. The message names the missing
tool and the command that installs it, because a refusal a person cannot act on is a refusal they
will route around.

**``stale`` is what makes the fast/slow split honest.** The hook measures the fast metrics at every
commit and *reads* the slow ones from the last ``make ci``. Without staleness the split would
quietly become a way of never measuring the slow half at all: a figure from three weeks ago would
gate today's commit and nobody would know. On dev it is a notification; on prod it refuses, and the
message says `run make ci`. A prod commit is usually a deliberate merge and paying minutes for it
once is the price of the number being true.

Two of the things gated here are not numbers and have no threshold: the **outcome of a test suite**,
which the caller reports with ``--suite name:passed|failed``, and the **fingerprint/version rule**.
They are conditions, and they are printed under the metric table rather than inside it.

What may refuse is a threshold, a suite and the fingerprint rule. **Grant integrity never refuses,
on any branch** -- that rule is unchanged and deliberate: a granted reference output regenerated by
``make-tests`` is ordinary work, and a contributor who does not hold the granting key could not
clear such a gate at all.
"""

from freeports_dev.ci import metrics
from freeports_dev.ci import suites as ci_suites


#: Measured, and at or above the minimum.
PASS = "pass"

#: Measured, and under it.
BELOW = "below"

#: Nobody could compute it. Never a pass.
UNMEASURED = "unmeasured"

#: Computed, but at a commit that is not this one.
STALE = "stale"

#: No minimum is configured, so there is nothing to fail.
NO_THRESHOLD = "no threshold"

#: The verdicts that stop a commit on a prod branch, in the order the summary explains them.
_REFUSING = (BELOW, UNMEASURED, STALE)


class Verdict:
    """One metric's line in the table: what was asked, what was found, and what that means."""

    def __init__(
        self, metric, measurement=None, minimum=None, state=NO_THRESHOLD, reason=None
    ):
        self.metric = metric
        self.measurement = measurement
        self.minimum = minimum
        self.state = state
        self.reason = reason

    @property
    def value(self):
        return self.measurement.value if self.measurement is not None else None

    @property
    def unit(self):
        return self.measurement.unit if self.measurement is not None else None

    @property
    def fails(self):
        """Whether this line would refuse a commit on a prod branch."""
        return self.state in _REFUSING


#: The suite ran at this commit and passed.
RAN = "ran"

#: The suite ran at this commit and something in it did not pass.
BROKE = "broke"

#: The suite last ran at another commit. Says nothing about this code.
SUITE_STALE = "stale"

#: Nobody has run it here at all.
NOT_RUN = "not run"

#: The suite states that stop a commit on a prod branch.
#:
#: ``not run`` and ``stale`` are in this list for the reason ``unmeasured`` is in the metric one:
#: **a suite nobody ran is not a suite that passed.** Leaving them out would make the fast/slow
#: split a way of never running the slow half -- the gate would report "tests: ok" on the strength
#: of a quarter of them, which is worse than reporting nothing.
_SUITE_REFUSING = (BROKE, SUITE_STALE, NOT_RUN)

#: Every state a suite can be in, which is how a suite's line is told from a plain yes/no rule's.
_SUITE_STATES = (RAN,) + _SUITE_REFUSING


class Condition:
    """Something gated that is not a number: a suite's outcome, or the fingerprint rule.

    ``state`` is what a suite has and a plain yes/no rule does not. A rule either holds or it does
    not; a suite can also be stale or never have been run here, and those are different things to
    tell somebody -- one means "fix the code", the others mean "run the command", and ``command``
    carries which command.
    """

    def __init__(
        self,
        name,
        ok,
        detail=None,
        applicable=True,
        state=None,
        command=None,
        cost=None,
    ):
        self.name = name
        self.ok = ok
        self.detail = detail
        self.applicable = applicable
        self.state = state if state is not None else (RAN if ok else BROKE)
        self.command = command
        self.cost = cost

    @property
    def fails(self):
        """Whether this line stops a commit on a prod branch.

        A suite is judged by its state rather than by ``ok`` so that ``stale`` and ``not run``
        carry their own weight: they refuse, for the reason ``unmeasured`` refuses among the
        metrics. A plain rule has only the yes and the no.
        """
        if not self.applicable:
            return False
        if self.state in _SUITE_STATES:
            return self.state in _SUITE_REFUSING
        return not self.ok


def judge_suite(suite, outcome, head=None):
    """One suite's line, in the order the failures have to be checked.

    Never run is decided before staleness and both before the outcome, because each answers a
    question the next presupposes: there is no point asking when a suite ran if it never has, and
    none asking whether it passed if what passed was other code.
    """
    where = f"Run `{suite.command}`."
    if outcome is None:
        because = f", because {suite.expense}" if suite.expense else ""
        return Condition(
            suite.name,
            False,
            f"never run in this repository{because}. {where}",
            state=NOT_RUN,
            command=suite.command,
            cost=suite.cost,
        )

    if head and outcome.head and outcome.head != head:
        return Condition(
            suite.name,
            False,
            f"last run at {outcome.head[:8]}, not at HEAD ({head[:8]}). {where}",
            state=SUITE_STALE,
            command=suite.command,
            cost=suite.cost,
        )

    if not outcome.passed:
        return Condition(
            suite.name,
            False,
            f"did not pass. {where}",
            state=BROKE,
            command=suite.command,
            cost=suite.cost,
        )

    return Condition(
        suite.name, True, state=RAN, command=suite.command, cost=suite.cost
    )


def judge_metric(name, measurement, minimum, head=None):
    """The verdict for one metric, in the order the failures have to be checked.

    Unmeasured is decided before staleness and both before the comparison, because each answers a
    question the next one presupposes: there is no point asking whether a figure is current if
    nobody could compute it, and none asking whether it clears a bar if it describes other code.
    """
    if minimum is None:
        return Verdict(name, measurement, None, NO_THRESHOLD)

    if measurement is None:
        return Verdict(
            name,
            None,
            minimum,
            UNMEASURED,
            "nothing in reports/ answers for it. Run the command that measures it.",
        )

    if not measurement.is_measured:
        return Verdict(name, measurement, minimum, UNMEASURED, measurement.reason)

    # A measurement with no commit recorded, or a repository with no commit to compare against,
    # cannot be judged stale -- and guessing would refuse commits in a repository that has simply
    # never been committed to.
    if head and measurement.head and measurement.head != head:
        return Verdict(
            name,
            measurement,
            minimum,
            STALE,
            f"measured at {measurement.head[:8]}, not at HEAD ({head[:8]}). Run `make ci`.",
        )

    if measurement.value < minimum:
        return Verdict(
            name,
            measurement,
            minimum,
            BELOW,
            f"{_precise(measurement)} is under the minimum of {minimum:g}.",
        )

    return Verdict(name, measurement, minimum, PASS)


def _precise(measurement):
    """A figure printed at the precision its unit is actually judged at.

    A lint score is a ratchet held just under ten, so two decimals round 9.998 to ``10.00`` and the
    explanation then reads "10.00 is under the minimum of 10" — which looks like a bug in the tool
    rather than a figure in the code, and would send somebody looking in the wrong place.
    """
    if measurement.unit == "score":
        return f"{measurement.value:.3f}"
    return f"{measurement.value:.2f}"


def _package_overrides(thresholds):
    """Which aggregate each per-package minimum removes a package from.

    A package with its own minimum leaves the aggregate's denominator, so the two can never
    contradict each other -- the aggregate is then a statement about everything nobody named.
    """
    overrides = {}
    for name in thresholds:
        split = metrics.split_package_key(name)
        if split is not None:
            aggregate, package = split
            overrides.setdefault(aggregate, set()).add(package)
    return overrides


class Gate:
    """The whole verdict: every metric, every condition, and the exit status they add up to."""

    def __init__(self, branch_class, verdicts, conditions=None, skipped_slow=None):
        self.branch_class = branch_class
        self.verdicts = list(verdicts)
        self.conditions = list(conditions or [])
        self.skipped_slow = list(skipped_slow or [])

    @property
    def failures(self):
        return [v for v in self.verdicts if v.fails] + [
            c for c in self.conditions if c.fails
        ]

    @property
    def refuses(self):
        """Whether this commit is stopped.

        Only on a prod branch, and only for a threshold, a suite or the fingerprint rule. On dev
        every one of these is a notification, which is what was asked and is a change from the
        behaviour the engine's hook had before this work.
        """
        return self.branch_class.refuses and bool(self.failures)

    @property
    def exit_status(self):
        return 1 if self.refuses else 0


def evaluate(
    config,
    measurements,
    conditions=None,
    head=None,
    skipped_slow=None,
    suite_outcomes=None,
    reported_suites=None,
):
    """Judge every metric this repository can answer for, plus the conditions it was told about.

    A metric with no minimum is still listed. Being able to see a figure nobody has decided about
    yet is how a threshold gets seeded at a real number instead of an aspiration -- which is the
    mistake the pipeline this replaces made, asking 90 % of a figure that read 25.93 %.
    """
    thresholds = config.thresholds()
    branch_class = config.branch_class()
    overrides = _package_overrides(thresholds)

    names = []
    for metric in (
        metrics.known_in(config.repo_kind) if config.repo_kind else metrics.REGISTRY
    ):
        if metric.is_family:
            continue
        names.append(metric.pattern)
    for name in thresholds:
        if name not in names:
            names.append(name)
    for name in measurements:
        if name not in names:
            names.append(name)

    verdicts = []
    for name in names:
        verdict = judge_metric(name, measurements.get(name), thresholds.get(name), head)
        if name in overrides and verdict.measurement is not None:
            verdict.reason = _note_overrides(verdict.reason, overrides[name])
        verdicts.append(verdict)

    return Gate(
        branch_class,
        verdicts,
        _suite_conditions(config, suite_outcomes, reported_suites, head)
        + list(conditions or []),
        skipped_slow,
    )


def _suite_conditions(config, suite_outcomes, reported_suites, head):
    """One line per suite this repository has, whether or not anybody ran it.

    **Every suite is listed, not only the ones with an answer.** That is the whole point of the
    registry: a gate that prints what it ran tells you nothing about what it did not, and the
    suites it did not run are exactly the ones a person needs reminding of. A repository is asked
    only about the suites its kind actually has, the same rule the metric table follows.

    ``reported_suites`` is what the caller says happened just now, and it wins over the recorded
    file for that suite -- a run in progress is more current than a run on disk, and by definition
    it happened at HEAD.
    """
    from freeports_dev.ci import report as ci_report

    recorded = dict(suite_outcomes or {})
    for name, outcome in (reported_suites or {}).items():
        recorded[name] = ci_report.SuiteOutcome(name, outcome, head=head)

    known = (
        ci_suites.known_in(config.repo_kind) if config.repo_kind else ci_suites.REGISTRY
    )
    lines = [judge_suite(suite, recorded.get(suite.name), head) for suite in known]

    # A suite nobody has heard of, reported or recorded anyway. Listed rather than dropped: the one
    # unacceptable outcome here is a suite that ran and was silently not counted.
    for name in sorted(recorded):
        if ci_suites.find(name) is None:
            outcome = recorded[name]
            passed = outcome.passed
            lines.append(
                Condition(
                    name,
                    passed,
                    None if passed else "did not pass",
                    state=RAN if passed else BROKE,
                )
            )
    return lines


def _note_overrides(reason, packages):
    note = "packages with their own minimum: " + ", ".join(sorted(packages))
    return f"{reason} ({note})" if reason else note


# -- rendering -------------------------------------------------------------------------------


def _format_value(verdict):
    if verdict.value is None:
        return "—"
    return (
        f"{verdict.value:.1f} %"
        if verdict.unit == "percent"
        else f"{verdict.value:.3f}"
    )


def _format_minimum(verdict):
    if verdict.minimum is None:
        return "—"
    return (
        f"{verdict.minimum:.1f} %"
        if verdict.unit == "percent"
        else f"{verdict.minimum:.3f}"
    )


#: How a suite's state prints. The two that are not a pass and not a failure print as loudly as a
#: failure does, because on a prod branch they refuse just as hard -- and on a dev branch they are
#: the line a person is meant to notice and act on.
_CONDITION_LABEL = {
    RAN: "ran",
    BROKE: "FAILED",
    SUITE_STALE: "STALE",
    NOT_RUN: "NOT RUN",
}

_VERDICT_LABEL = {
    PASS: "pass",
    BELOW: "BELOW",
    UNMEASURED: "NOT MEASURED",
    STALE: "STALE",
    NO_THRESHOLD: "not gated",
}


def render_text(gate):
    """One table, then one sentence per line that did not pass.

    The sentences are the part that matters. A table of verdicts tells somebody a commit was
    refused; a sentence naming the tool, the figure and the command tells them what to do about it,
    and only the second kind of message survives contact with a person in a hurry.
    """
    lines = []
    enforcement = (
        "thresholds are enforced"
        if gate.branch_class.refuses
        else "thresholds are reported, not enforced"
    )
    where = (
        f"branch {gate.branch_class.branch}"
        if gate.branch_class.branch
        else "no branch"
    )
    lines.append(f"{where} -> {gate.branch_class.name}   ({enforcement})")
    lines.append(f"  {gate.branch_class.reason}")
    lines.append("")
    lines.append(f"{'metric':<38}{'measured':>10}{'minimum':>10}   verdict")
    for verdict in gate.verdicts:
        lines.append(
            f"{verdict.metric:<38}{_format_value(verdict):>10}{_format_minimum(verdict):>10}"
            f"   {_VERDICT_LABEL[verdict.state]}"
        )

    if gate.conditions:
        lines.append("")
        lines.append(f"{'suite':<38}{'cost':>10}{'':>10}   verdict")
        for condition in gate.conditions:
            if not condition.applicable:
                state = "not applicable"
            else:
                state = _CONDITION_LABEL.get(
                    condition.state, "ok" if condition.ok else "FAILED"
                )
            cost = condition.cost or ""
            lines.append(f"{condition.name:<38}{cost:>10}{'':>10}   {state}")

    explained = [v for v in gate.verdicts if v.fails and v.reason]
    if explained or gate.failures:
        lines.append("")
        for verdict in explained:
            lines.append(f"{verdict.metric} — {verdict.reason}")
        for condition in gate.conditions:
            if condition.fails and condition.detail:
                lines.append(f"{condition.name} — {condition.detail}")

    if gate.skipped_slow:
        lines.append("")
        lines.append(
            "skipped, because --skip-slow was given: "
            + ", ".join(sorted(gate.skipped_slow))
        )
        lines.append(
            "Those figures were not checked at all. This is never the default."
        )

    if gate.failures and not gate.branch_class.refuses:
        lines.append("")
        lines.append(
            "On a dev branch these are warnings. On a prod branch each one refuses the commit — "
            "a figure nobody could compute is not a figure above the threshold."
        )
    elif gate.refuses:
        lines.append("")
        lines.append(
            f"Refused: {len(gate.failures)} of the repository's own rules are not met."
        )

    return "\n".join(lines)


def render_json(gate):
    import json

    return json.dumps(
        {
            "branch": gate.branch_class.branch,
            "class": gate.branch_class.name,
            "reason": gate.branch_class.reason,
            "enforced": gate.branch_class.refuses,
            "refused": gate.refuses,
            "exit_status": gate.exit_status,
            "skipped_slow": sorted(gate.skipped_slow),
            "metrics": [
                {
                    "metric": v.metric,
                    "value": v.value,
                    "unit": v.unit,
                    "minimum": v.minimum,
                    "verdict": v.state,
                    "reason": v.reason,
                    "head": v.measurement.head if v.measurement is not None else None,
                }
                for v in gate.verdicts
            ],
            "conditions": [
                {
                    "name": c.name,
                    "ok": c.ok,
                    "applicable": c.applicable,
                    "detail": c.detail,
                    "state": c.state,
                    "cost": c.cost,
                    "command": c.command,
                }
                for c in gate.conditions
            ],
        },
        indent=2,
        sort_keys=True,
    )


def parse_suite(text):
    """``--suite rust.unit:passed`` into a name and an outcome, for the run happening *now*.

    What is given on the command line describes this moment, so it outranks whatever the same suite
    left in ``reports/`` at some earlier commit. Anything that is not exactly ``passed`` is a
    failure, including a spelling nobody intended: a hook writes this string from a shell variable,
    and the one way this must not fail is by reading an unrecognised word as success.

    A name no registry claims is still honoured rather than dropped. A repository may run a suite
    this workspace has never heard of, and swallowing it would be the one failure mode that matters
    -- a suite reported as passing because nobody recognised its name.
    """
    return ci_suites.parse(text)
