"""``freeports-dev ci-report``: what a gate run looks like once it is written down.

The measurement commands establish facts and write them into ``reports/``; :mod:`freeports_dev.ci.gate`
judges them; this renders the judgement, and does nothing else. That is the same three-way split
``freeports-validate`` follows — ``collect``, ``report``, ``check-grants`` — and it is here for the
same reason: a rendering that measured something of its own would be a second source of truth for a
figure the gate already decided about.

Every rendering is a pure function of the model, which is why the model exists at all::

    $ freeports-dev ci-report --format json | jq '.metrics[] | select(.verdict != "pass")'
    $ freeports-dev ci-report --format html     --out docs/source/_extra/ci/report.html
    $ freeports-dev ci-report --format badges   --out ci/report/badges/
    $ freeports-dev ci-report --format markdown --out README.md
    $ freeports-dev ci-report --format rst --table breakdown --out docs/source/dev/ci-report/breakdown.rst

The first of those answers questions no rendering here anticipated, and it stays available however
the others change.

**This command never refuses anything.** ``ci-check`` decides whether a commit is made; this says
what the run found, and exits non-zero only when it could not write what it was asked to write. A
hook that could be stopped by its own report would be a hook people remove.

**Nothing here carries a timestamp, and no rendering names a commit unless a figure is stale.**
These artefacts are committed — badges in a ``README.md``, tables in a documentation tree — and a
date, or the head recorded beside every figure, would put a diff in every commit saying nothing had
changed. The commit is named in exactly the place where it is the news: beside a figure that was
measured at another one.
"""

import html
import json
from pathlib import Path

from freeports_dev.ci import gate as ci_gate
from freeports_dev.ci import metrics


#: What a rendering may be asked for. ``json`` is the model itself, and is first because it is the
#: one that outlives this file.
FORMATS = ("json", "html", "badges", "markdown", "rst")

#: The lines a rewritable file must already contain, per format. Ordinary comments in both
#: languages, so a file carrying them renders exactly as it did before anything was written between
#: them. They say ``freeports-dev`` where the grants report says ``freeports-validate``: one file
#: may well carry both blocks, and a marker that did not name its writer would have them overwrite
#: each other.
MARKERS = {
    "markdown": ("<!-- freeports-dev:begin -->", "<!-- freeports-dev:end -->"),
    "rst": (".. freeports-dev:begin", ".. freeports-dev:end"),
}

#: Where a reader goes to find out what any of this is worth: the page that explains the gate, not
#: the table that ran it.
GATE_DOC_URL = "https://docs.freeports.org/en/stable/dev/ci.html"

#: The sentence every rendering carries, and the reason it is not optional.
#:
#: A page of percentages invites exactly one misreading — that somebody has certified the software —
#: and a coverage figure is the easiest number in this project to mistake for a guarantee. What a
#: report shows is what one run measured, on one machine, with whatever tools that machine had. It
#: is evidence a reader can reproduce, and the only way to be sure of a line in it is to re-run the
#: command that measured it.
NOTICE = (
    "Generated by `freeports-dev ci-report`, and demonstrative: it shows what one run measured "
    "on one machine, not that the software is correct. To be sure of any line, re-run the command "
    "that measures it and `freeports-dev ci-check` yourself."
)

NOTICE_LINK_TEXT = "What is gated here, and what refuses: the commit gate"

WRITTEN_BY = (
    "Written by `freeports-dev ci-report`. Anything between the markers is replaced."
)

#: Every gated figure measured, current, and at or above its minimum.
PASSING = "passing"

#: A measured figure under its minimum, or a suite that did not pass.
FAILING = "failing"

#: Nothing below, but something nobody could compute, something taken at another commit, or
#: something a ``--skip-slow`` run did not look at.
#:
#: Grey, and never a pass. A figure nobody could compute is not a figure above the threshold — the
#: rule :mod:`freeports_dev.ci.gate` already applies, and the same one the grants report applies to
#: a methodology page it could not reach.
INCONCLUSIVE = "inconclusive"

#: How many breakdown lines per metric a *document* shows, when no tier says otherwise.
#:
#: Fifteen, because the question a breakdown answers is "what would I fix first" and nobody fixes
#: the hundred and twentieth file. ``0`` means all of them, and ``--format json`` always carries all
#: of them whatever this says.
DEFAULT_BREAKDOWN_LIMIT = 15

#: Shields' own palette, so a badge generated here sits beside one fetched from shields.io without
#: the two looking like they came from different projects.
COLORS = {
    "brightgreen": "#4c1",
    "green": "#97ca00",
    "yellow": "#dfb317",
    "orange": "#fe7d37",
    "red": "#e05d44",
    "blue": "#007ec6",
    "grey": "#9f9f9f",
}

#: What the one-word status of a run is worth on a badge.
STATUS_COLORS = {PASSING: "brightgreen", FAILING: "red", INCONCLUSIVE: "grey"}

#: How each verdict is written outside the terminal. ``ci-check``'s own labels shout, which is right
#: on a console at the moment a commit is refused and wrong in a document somebody reads later.
VERDICT_LABEL = {
    ci_gate.PASS: "pass",
    ci_gate.BELOW: "below",
    ci_gate.UNMEASURED: "not measured",
    ci_gate.STALE: "stale",
    ci_gate.NO_THRESHOLD: "not gated",
}

#: What each verdict means, printed as the legend of every rendering that shows verdicts.
VERDICT_LEGEND = {
    ci_gate.PASS: "measured, current, and at or above the minimum this repository asks for.",
    ci_gate.BELOW: "measured, and under that minimum.",
    ci_gate.UNMEASURED: "nobody could compute it — the tool is missing, or its run failed. "
    "Never a pass.",
    ci_gate.STALE: "computed, but at a commit other than this one, so it describes other code.",
    ci_gate.NO_THRESHOLD: "reported, with no minimum configured for it: it gates nothing.",
}


#: How each verdict is counted in ``totals``. A key rather than the verdict itself, because
#: ``no threshold`` carries a space and a JSON key somebody has to quote in ``jq`` is a key somebody
#: gets wrong; ``ungated`` says the same thing in one word.
TOTAL_KEY = {
    ci_gate.PASS: "pass",
    ci_gate.BELOW: "below",
    ci_gate.UNMEASURED: "unmeasured",
    ci_gate.STALE: "stale",
    ci_gate.NO_THRESHOLD: "ungated",
}


class MarkersMissing(Exception):
    """A file to be rewritten does not say where the report goes.

    Deliberately not "append it at the end". Where a table belongs in a README is a judgement about
    that README, and a command that guessed would put one under a licence notice once and then keep
    it there for ever.
    """


# ---------------------------------------------------------------------------
# The model
# ---------------------------------------------------------------------------


def _cost_of(name):
    metric = metrics.find(name)
    return metric.cost if metric is not None else None


def _description_of(name):
    metric = metrics.find(name)
    return metric.description if metric is not None else None


def _within(root, item):
    """A breakdown key with the machine taken out of it.

    ``cargo llvm-cov`` reports absolute paths, so a breakdown taken here reads
    ``/home/somebody/work/analysis_finance_reports/packages/…`` — which names the person's home
    directory in a file the repository commits, and makes the same repository render differently on
    every machine that renders it. The key is a path *inside this repository* or it is not a path at
    all, and either way what belongs in the document is the part that is about the code.
    """
    if root is None or not isinstance(item, str):
        return item
    try:
        return str(Path(item).resolve().relative_to(Path(root).resolve()))
    except (ValueError, OSError):
        return item


def status_of(verdicts, conditions=(), skipped_slow=()):
    """The one word a badge carries, in the order the three cases have to be decided.

    ``failing`` first: a figure known to be under its minimum is the strongest thing this run can
    say, and one unmeasured metric beside it does not soften that. ``inconclusive`` second, and it
    covers the skipped figures too — a metric a ``--skip-slow`` run never looked at must not be
    mistaken afterwards for one that passed.

    **A run that gated nothing is inconclusive, not passing.** "Passing" means every gated figure
    cleared its minimum, and with no minima there is nothing that cleared anything — a green badge
    on a repository nobody has configured is the vacuous truth this whole mechanism exists to keep
    out of a README. It is also the first state of every repository `init-format-repo` creates, and
    it says so.
    """
    if any(v.state == ci_gate.BELOW for v in verdicts) or any(
        c.fails for c in conditions
    ):
        return FAILING
    if (
        any(v.state in (ci_gate.UNMEASURED, ci_gate.STALE) for v in verdicts)
        or skipped_slow
    ):
        return INCONCLUSIVE
    if not any(v.minimum is not None for v in verdicts):
        return INCONCLUSIVE
    return PASSING


def build(gate, config=None, name=None):
    """The model of one gate run: every metric, every condition, and what they add up to.

    It carries what the gate decided *and* what the registry knows about each metric — its cost
    class and the sentence saying what it measures. A table reading ``docs.rust 39.4 %`` and nothing
    else tells a reader a number and not what was counted, and the reader of a documentation page
    has no ``--help`` to hand.
    """
    branch_class = gate.branch_class
    root = config.root if config is not None else None
    entries = []
    for verdict in gate.verdicts:
        measurement = verdict.measurement
        entries.append(
            {
                "metric": verdict.metric,
                "value": verdict.value,
                "unit": verdict.unit,
                "minimum": verdict.minimum,
                "verdict": verdict.state,
                "reason": verdict.reason,
                "cost": _cost_of(verdict.metric),
                "description": _description_of(verdict.metric),
                "head": measurement.head if measurement is not None else None,
                "breakdown": (
                    {_within(root, k): v for k, v in measurement.breakdown.items()}
                    if measurement is not None
                    else {}
                ),
                "detail": dict(measurement.detail) if measurement is not None else {},
            }
        )

    counts = {key: 0 for key in TOTAL_KEY.values()}
    for entry in entries:
        counts[TOTAL_KEY[entry["verdict"]]] += 1

    return {
        "repository": {
            "name": name or (config.root.name if config is not None else None),
            "kind": config.repo_kind if config is not None else None,
        },
        "branch": {
            "name": branch_class.branch,
            "class": branch_class.name,
            "reason": branch_class.reason,
            "enforced": branch_class.refuses,
        },
        "status": status_of(gate.verdicts, gate.conditions, gate.skipped_slow),
        "breakdown_limit": (
            config.breakdown_limit if config is not None else DEFAULT_BREAKDOWN_LIMIT
        ),
        "refused": gate.refuses,
        "totals": {
            "metrics": len(entries),
            "gated": sum(1 for e in entries if e["minimum"] is not None),
            **counts,
        },
        "metrics": entries,
        "conditions": [
            {
                "name": condition.name,
                "ok": condition.ok,
                "applicable": condition.applicable,
                "detail": condition.detail,
            }
            for condition in gate.conditions
        ],
        "skipped_slow": sorted(gate.skipped_slow),
    }


# ---------------------------------------------------------------------------
# Reading the model
# ---------------------------------------------------------------------------


def _figure(entry, key="value"):
    """A figure at the precision its unit is judged at, or the dash that means there is none.

    A lint score is a ratchet held just under ten, so it is printed at three decimals: two would
    round 9.998 to ``10.00`` beside a minimum of 10, which reads as a bug in the tool rather than a
    figure in the code.
    """
    value = entry.get(key)
    if value is None:
        return "—"
    if entry.get("unit") == "score":
        return f"{value:.3f}"
    if entry.get("unit") == "percent":
        return f"{value:.1f} %"
    return f"{value:g}"


def _plural(count, singular, plural):
    """``1 metric`` / ``2 metrics``, written out rather than parenthesised.

    ``metric(s)`` costs nothing to produce and makes every sentence slightly harder to read than it
    needs to be, in a document whose whole purpose is to be read.
    """
    return f"{count} {singular if count == 1 else plural}"


def _tally(model):
    """The non-zero verdict counts, in the order the gate explains them.

    Zeroes are left out. "0 stale" in a summary line is a sentence about nothing, and four of them
    push the one number that matters off the end of the line.
    """
    totals = model["totals"]
    parts = []
    for state, word in (
        (ci_gate.PASS, "pass"),
        (ci_gate.BELOW, "below the minimum"),
        (ci_gate.UNMEASURED, "not measured"),
        (ci_gate.STALE, "measured at another commit"),
    ):
        count = totals.get(TOTAL_KEY[state])
        if count:
            parts.append(f"{count} {word}")
    return parts or ["nothing gated yet"]


def _enforcement(model):
    return (
        "thresholds are enforced"
        if model["branch"]["enforced"]
        else "thresholds are reported, not enforced"
    )


def _where(model):
    branch = model["branch"]
    return f"branch {branch['name']}" if branch["name"] else "no branch checked out"


def summary(model):
    """The one sentence every rendering opens with."""
    totals = model["totals"]
    return (
        f"{_plural(totals['metrics'], 'metric', 'metrics')}, {totals['gated']} gated: "
        f"{', '.join(_tally(model))}; "
        f"{_where(model)} → {model['branch']['class']} ({_enforcement(model)}); "
        f"ci-check: {model['status']}"
    )


def failing_conditions(model):
    """The conditions that did not hold — a suite that failed, a rule that was broken.

    They are not metrics: they have no unit, no minimum and nothing to plot, so every rendering
    prints them as sentences under the table rather than inventing table cells for them.
    """
    return [c for c in model["conditions"] if c["applicable"] and not c["ok"]]


def explained(model):
    """Every metric that did not pass and has something to say about why.

    The sentences are the part that matters. A table of verdicts tells somebody a figure is wrong;
    a sentence naming the tool, the number and the command tells them what to do about it.
    """
    return [
        entry
        for entry in model["metrics"]
        if entry["verdict"] in (ci_gate.BELOW, ci_gate.UNMEASURED, ci_gate.STALE)
        and entry["reason"]
    ]


def _by_reason(model):
    """The failures, one sentence per *reason* rather than one per metric.

    A repository whose last full run was two commits ago has the same staleness sentence twelve
    times over, and twelve copies of one fact push everything else off the page. Metrics sharing a
    reason share a line, in the order the table lists them; two metrics whose reasons differ by so
    much as the note about a per-package minimum still get their own, because at that point the
    sentences are no longer the same fact.
    """
    grouped = {}
    for entry in explained(model):
        grouped.setdefault(entry["reason"], []).append(entry["metric"])
    return list(grouped.items())


def _legend_states(model):
    """The verdicts actually on the table, so the legend explains those and no others.

    A page gains nothing from the explanation of a word it does not contain, and the next reader
    would have to check whether it was stale.
    """
    seen = []
    for entry in model["metrics"]:
        if entry["verdict"] not in seen:
            seen.append(entry["verdict"])
    return [state for state in VERDICT_LABEL if state in seen]


# ---------------------------------------------------------------------------
# The tables
# ---------------------------------------------------------------------------


class Table:
    """One arrangement of the same run: what it is called, and what its columns are."""

    def __init__(self, heading, prose, headers, alignment):
        self.heading = heading
        self.prose = prose
        self.headers = headers
        self.alignment = alignment


#: The three values of ``--table``. ``summary`` is first because it is the default and the one a
#: README carries; the other two are the two questions it provokes — *what is being asked of this
#: repository*, and *where does a figure that fell short actually come from*.
TABLES = {
    "summary": Table(
        "What this run measured",
        "The same table as `freeports-dev ci-check`, for the repository as a whole.",
        ("Metric", "Measured", "Minimum", "Verdict"),
        ("---", "---:", "---:", "---"),
    ),
    "thresholds": Table(
        "What a commit here has to clear",
        "Every minimum this repository declares, what it is a minimum *of*, and whether it is "
        "measured at every commit or read from the last full run.",
        ("Metric", "Minimum", "Measured", "Cost", "What it measures"),
        ("---", "---:", "---:", "---", "---"),
    ),
    "breakdown": Table(
        "Where each figure comes from",
        "The detail each measurement already carries, worst first: the files that pull a coverage "
        "figure down, and the rules a lint score is spent on. A line with nothing to answer for — "
        "a document that does have a whole-document test — is not listed at all.",
        ("Metric", "Item", "Figure"),
        ("---", "---", "---:"),
    ),
}

#: The default, and what a caller that says nothing is asking for.
DEFAULT_TABLE = "summary"


def _summary_rows(model):
    for entry in model["metrics"]:
        yield (
            entry["metric"],
            _figure(entry),
            _figure(entry, "minimum"),
            VERDICT_LABEL[entry["verdict"]],
        )


def _threshold_rows(model):
    """Only the gated metrics, because a minimum is what this table is about.

    A metric nobody set a minimum for is in the summary, where it is visible and says "not gated" —
    which is how a threshold eventually gets seeded at a figure somebody has actually seen.
    """
    for entry in model["metrics"]:
        if entry["minimum"] is None:
            continue
        yield (
            entry["metric"],
            _figure(entry, "minimum"),
            _figure(entry),
            entry["cost"] or "—",
            entry["description"] or "—",
        )


#: How many members of a list-valued breakdown a line spells out before it stops counting them.
#: A format with two hundred tested pages has said everything it has to say by the tenth.
_LIST_SHOWN = 8


def _breakdown_value(entry, value):
    """One line of a breakdown, formatted by what that breakdown actually holds.

    The measurements do not all break down into the same kind of thing, and pretending they do is
    how a renderer crashes on a repository it was not written against. Four shapes occur today:

    ==============================  ===========================  ====================
    metric                          a value is                   read as
    ==============================  ===========================  ====================
    ``docs.*``, ``tests.*.lines``   a percentage                 ``72.9 %``
    ``lint.*``                      a count of findings          ``4``
    ``tests.formats.integration``   whether a test exists        ``yes`` / ``no``
    ``tests.formats.single_page``   which pages carry a fixture  ``2 pages: 13, 14``
    ==============================  ===========================  ====================

    Anything else is printed as it stands rather than guessed at. A breakdown is written by the
    command that measured it, and a renderer that insisted on a shape would be the thing standing
    between a new metric and being visible at all.
    """
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, (list, tuple)):
        shown = ", ".join(str(item) for item in value[:_LIST_SHOWN])
        more = (
            "" if len(value) <= _LIST_SHOWN else f", +{len(value) - _LIST_SHOWN} more"
        )
        return (
            f"{_plural(len(value), 'page', 'pages')}: {shown}{more}"
            if value
            else "none"
        )
    if isinstance(value, (int, float)):
        if entry.get("unit") == "percent":
            return f"{value:.1f} %"
        if isinstance(value, float) and value.is_integer():
            return str(int(value))
        return f"{value:g}"
    return str(value)


def _goodness(entry, value):
    """How well one breakdown line is doing, on whatever scale that line is on.

    One number so that every breakdown can be sorted worst first by the same rule, and signed so
    that "worst" is always the low end -- a count of lint findings is the one quantity here where a
    bigger number is a worse repository, and negating it is cheaper than a second sort order that
    somebody would eventually apply to the wrong metric.
    """
    if isinstance(value, bool):
        return 0 if not value else 1
    if isinstance(value, (list, tuple)):
        return len(value)
    if isinstance(value, (int, float)):
        return -value if entry.get("unit") == "score" else value
    return 0


def _worst_first(entry):
    """One metric's breakdown, worst first.

    Ties are broken by name, so two runs of the same repository produce the same file and a
    committed page does not churn on dictionary order.
    """
    return sorted(
        (entry.get("breakdown") or {}).items(),
        key=lambda item: (_goodness(entry, item[1]), item[0]),
    )


def _answers_for_something(value):
    """Whether a breakdown line has anything to answer for.

    A yes/no breakdown — "does this document have a whole-document test at all" — says everything
    it has to say in its *no* lines. Listing the thirty-one documents that do have one pads the page
    with rows nobody acts on and pushes the five that need attention off the top of it, and the
    proportion is already the metric's own figure. Every other shape of value stays: a file at 100 %
    is worth seeing beside one at 12 %, because there the number *is* the answer.
    """
    return not (isinstance(value, bool) and value)


def _document_lines(entry):
    """The breakdown lines of one metric that a document would show, worst first."""
    return [item for item in _worst_first(entry) if _answers_for_something(item[1])]


def _breakdown_rows(model):
    """The breakdown lines a *document* carries, which is not all of them.

    The crate alone breaks down into a hundred and twenty files, and a page listing every one of
    them changes in every commit that moves any of them — a committed file whose diff nobody can
    read is a committed file nobody reads. So a document shows the worst few per metric, which is
    the end somebody would act on, and says how many it left out. The model keeps all of them:
    ``--format json`` is the complete answer, and it is the one that does not go in a commit.
    """
    limit = model.get("breakdown_limit") or 0
    for entry in model["metrics"]:
        items = _document_lines(entry)
        for item, value in items[:limit] if limit else items:
            yield entry["metric"], item, _breakdown_value(entry, value)


def breakdown_omitted(model):
    """How many breakdown lines each metric has that a document does not show."""
    limit = model.get("breakdown_limit") or 0
    if not limit:
        return []
    return [
        (entry["metric"], len(_document_lines(entry)) - limit)
        for entry in model["metrics"]
        if len(_document_lines(entry)) > limit
    ]


ROWS = {
    "summary": _summary_rows,
    "thresholds": _threshold_rows,
    "breakdown": _breakdown_rows,
}


# ---------------------------------------------------------------------------
# JSON
# ---------------------------------------------------------------------------


def render_json(model):
    return json.dumps(model, indent=2, sort_keys=False) + "\n"


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------

#: Everything the page needs to look like a page. Inline, and it has to stay inline: a report that
#: went to a content delivery network for its stylesheet would render as unformatted text on exactly
#: the machines — an air-gapped build, a laptop on a train — this project already goes out of its
#: way to work on.
#:
#: A near-copy of the one `freeports-validate report` writes, and deliberately not shared with it:
#: the two packages are installed independently, and a formats repository may hold one and not the
#: other. A stylesheet is not worth a dependency between two commands that otherwise never import
#: each other.
STYLE = """
:root { color-scheme: light dark; --line: #d4d4d4; --muted: #6b6b6b;
        --ok: #1a7f37; --bad: #b42318; --unsure: #8a6d1f; }
@media (prefers-color-scheme: dark) {
  :root { --line: #3a3a3a; --muted: #9a9a9a;
          --ok: #4ac26b; --bad: #ff6a5e; --unsure: #d4a72c; } }
body { font: 15px/1.5 system-ui, sans-serif; margin: 0 auto; max-width: 62rem; padding: 2rem 1rem; }
h1 { font-size: 1.4rem; margin: 0 0 .25rem; }
p.summary { color: var(--muted); margin: 0 0 .75rem; }
p.notice { border-left: 3px solid var(--line); color: var(--muted); font-size: .88rem;
           margin: 0 0 1.5rem; padding: .1rem 0 .1rem .7rem; }
nav { border-bottom: 1px solid var(--line); display: flex; gap: .25rem; margin-bottom: 1rem; }
nav button { background: none; border: 0; border-bottom: 2px solid transparent; color: inherit;
             cursor: pointer; font: inherit; padding: .5rem .9rem; }
nav button[aria-selected="true"] { border-bottom-color: currentColor; font-weight: 600; }
input[type="search"] { border: 1px solid var(--line); border-radius: .3rem; font: inherit;
                       margin-bottom: 1rem; padding: .4rem .6rem; width: 100%; }
table { border-collapse: collapse; font-size: .92rem; width: 100%; }
th, td { border-bottom: 1px solid var(--line); padding: .4rem .5rem; text-align: left;
         vertical-align: top; }
th { font-weight: 600; }
td.n { text-align: right; font-variant-numeric: tabular-nums; }
code { font-size: .9em; overflow-wrap: anywhere; }
.state-pass { color: var(--ok); }
.state-below { color: var(--bad); }
.state-unmeasured, .state-stale { color: var(--unsure); }
.prose { color: var(--muted); margin: .2rem 0 0; }
.legend { color: var(--muted); font-size: .85rem; margin-top: 2rem; }
.legend dt { font-weight: 600; float: left; clear: left; margin-right: .4rem; }
.legend dd { margin: 0 0 .2rem; }
[hidden] { display: none !important; }
"""

#: The only behaviour the page has: switching viewpoint, and filtering rows by substring. Written
#: out rather than pulled from a framework for the same reason as the stylesheet, and kept small
#: enough to read in one screen.
SCRIPT = """
const tabs = document.querySelectorAll('nav button');
const panels = document.querySelectorAll('section[data-panel]');
tabs.forEach(function (tab) {
  tab.addEventListener('click', function () {
    tabs.forEach(function (other) {
      other.setAttribute('aria-selected', String(other === tab));
    });
    panels.forEach(function (panel) {
      panel.hidden = panel.dataset.panel !== tab.dataset.tab;
    });
  });
});
document.querySelector('input[type="search"]').addEventListener('input', function (event) {
  const needle = event.target.value.toLowerCase();
  document.querySelectorAll('tbody tr').forEach(function (row) {
    row.hidden = needle !== '' && !row.textContent.toLowerCase().includes(needle);
  });
});
"""

#: The three tabs, which are the three tables. A reader who has learned the `--table` names has
#: learned the page, and a page that invented a fourth arrangement would be teaching a second
#: vocabulary for the same run.
VIEWPOINTS = (
    ("summary", "Verdicts"),
    ("thresholds", "Thresholds"),
    ("breakdown", "Breakdown"),
)


def _e(value):
    """Escaped, and ``None`` rendered as the dash that means "nothing to say here"."""
    return html.escape("—" if value is None else str(value))


def _html_table(headers, rows, numeric=(), coded=()):
    head = "".join(f"<th>{_e(header)}</th>" for header in headers)
    body_rows = []
    for row in rows:
        cells = []
        for index, cell in enumerate(row):
            css = ' class="n"' if index in numeric else ""
            text = f"<code>{_e(cell)}</code>" if index in coded else _e(cell)
            cells.append(f"<td{css}>{text}</td>")
        body_rows.append("<tr>" + "".join(cells) + "</tr>")
    body = "\n".join(body_rows)
    if not body_rows:
        body = f'<tr><td colspan="{len(headers)}">Nothing to report yet.</td></tr>'
    return f"<table><thead><tr>{head}</tr></thead><tbody>\n{body}\n</tbody></table>"


def _summary_panel(model):
    rows = []
    for entry in model["metrics"]:
        rows.append(
            [
                f"<td><code>{_e(entry['metric'])}</code></td>",
                f'<td class="n">{_e(_figure(entry))}</td>',
                f'<td class="n">{_e(_figure(entry, "minimum"))}</td>',
                f'<td><span class="state-{_e(entry["verdict"])}">'
                f"{_e(VERDICT_LABEL[entry['verdict']])}</span>"
                + (
                    f'<p class="prose">{_e(entry["reason"])}</p>'
                    if entry["reason"]
                    else ""
                )
                + "</td>",
            ]
        )
    head = "".join(f"<th>{_e(h)}</th>" for h in TABLES["summary"].headers)
    body = "\n".join("<tr>" + "".join(row) + "</tr>" for row in rows)
    if not rows:
        body = '<tr><td colspan="4">Nothing has been measured yet.</td></tr>'
    return f"<table><thead><tr>{head}</tr></thead><tbody>\n{body}\n</tbody></table>"


def _thresholds_panel(model):
    return _html_table(
        TABLES["thresholds"].headers,
        list(_threshold_rows(model)),
        numeric={1, 2},
        coded={0},
    )


def _breakdown_panel(model):
    table = _html_table(
        TABLES["breakdown"].headers,
        list(_breakdown_rows(model)),
        numeric={2},
        coded={0, 1},
    )
    omitted = breakdown_omitted(model)
    if not omitted:
        return table
    listed = ", ".join(
        f"<code>{_e(metric)}</code> ({count} more)" for metric, count in omitted
    )
    return (
        f"{table}"
        f'<p class="legend">Only the worst {model["breakdown_limit"]} lines of each metric '
        f"are shown: {listed}. <code>freeports-dev ci-report --format json</code> carries every "
        "one of them.</p>"
    )


PANELS = {
    "summary": _summary_panel,
    "thresholds": _thresholds_panel,
    "breakdown": _breakdown_panel,
}


def _conditions_html(model):
    failed = failing_conditions(model)
    if not failed:
        return ""
    items = "".join(
        f"<li><strong>{_e(condition['name'])}</strong> — {_e(condition['detail'])}</li>"
        for condition in failed
    )
    return f'<div class="legend">Not a number, and not holding:<ul>{items}</ul></div>'


def _skipped_html(model):
    if not model["skipped_slow"]:
        return ""
    listed = ", ".join(f"<code>{_e(name)}</code>" for name in model["skipped_slow"])
    return (
        f'<p class="legend">Skipped, because <code>--skip-slow</code> was given: {listed}. '
        "Those figures were not checked at all, and this is never the default.</p>"
    )


def render_html(model):
    tabs = "".join(
        f'<button data-tab="{key}" aria-selected="{str(index == 0).lower()}">'
        f"{_e(label)}</button>"
        for index, (key, label) in enumerate(VIEWPOINTS)
    )
    sections = "\n".join(
        f'<section data-panel="{key}"{"" if index == 0 else " hidden"}>'
        f"{PANELS[key](model)}</section>"
        for index, (key, _label) in enumerate(VIEWPOINTS)
    )
    legend = "".join(
        f"<dt>{_e(VERDICT_LABEL[state])}</dt><dd>{_e(VERDICT_LEGEND[state])}</dd>"
        for state in _legend_states(model)
    )
    name = model["repository"]["name"] or "this repository"
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Continuous integration — {_e(name)}</title>
<style>{STYLE}</style>
</head>
<body>
<h1>Continuous integration — {_e(name)}</h1>
<p class="summary">{_e(summary(model))}</p>
<p class="notice">{_e(NOTICE)}
<a href="{_e(GATE_DOC_URL)}">{_e(NOTICE_LINK_TEXT)}</a>.</p>
<nav>{tabs}</nav>
<input type="search" placeholder="Filter rows…" aria-label="Filter rows">
{sections}
{_conditions_html(model)}
{_skipped_html(model)}
<dl class="legend">{legend}</dl>
<p class="legend">{_e(model["branch"]["reason"])}</p>
<script>{SCRIPT}</script>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Badges
# ---------------------------------------------------------------------------

#: Verdana at 11px, which is what shields measures against. An approximation is good enough here:
#: the consequence of being a pixel out is a badge with slightly wide padding, and the alternative
#: is shipping a font metrics table for a dozen short strings.
_CHARACTER_WIDTH = 7.0
_SIDE_PADDING = 10.0


def _badge_svg(label, message, color):
    """One shields-style badge, drawn here rather than fetched.

    Drawn locally so that generating a report needs no network: a command that fetched its own
    badges would fail in exactly the places this whole pipeline exists to keep working.
    """
    label_width = _CHARACTER_WIDTH * len(label) + _SIDE_PADDING * 2
    message_width = _CHARACTER_WIDTH * len(message) + _SIDE_PADDING * 2
    total = label_width + message_width
    label_middle = label_width / 2
    message_middle = label_width + message_width / 2
    fill = COLORS.get(color, COLORS["grey"])
    title = html.escape(f"{label}: {message}")
    label = html.escape(label)
    message = html.escape(message)
    return f"""<svg xmlns="http://www.w3.org/2000/svg" \
width="{total:.0f}" height="20" role="img" aria-label="{title}">
<title>{title}</title>
<linearGradient id="gradient" x2="0" y2="100%">
<stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
<stop offset="1" stop-opacity=".1"/>
</linearGradient>
<clipPath id="rounded"><rect width="{total:.0f}" height="20" rx="3" fill="#fff"/></clipPath>
<g clip-path="url(#rounded)">
<rect width="{label_width:.0f}" height="20" fill="#555"/>
<rect x="{label_width:.0f}" width="{message_width:.0f}" height="20" fill="{fill}"/>
<rect width="{total:.0f}" height="20" fill="url(#gradient)"/>
</g>
<g fill="#fff" text-anchor="middle" font-family="Verdana,DejaVu Sans,sans-serif" font-size="11">
<text x="{label_middle:.0f}" y="15" fill="#010101" fill-opacity=".3">{label}</text>
<text x="{label_middle:.0f}" y="14">{label}</text>
<text x="{message_middle:.0f}" y="15" fill="#010101" fill-opacity=".3">{message}</text>
<text x="{message_middle:.0f}" y="14">{message}</text>
</g>
</svg>
"""


def _endpoint(label, message, color):
    """The same badge as data, for anyone who would rather shields.io drew it."""
    return (
        json.dumps(
            {"schemaVersion": 1, "label": label, "message": message, "color": color},
            indent=2,
        )
        + "\n"
    )


def _scale_color(percentage):
    """The colour of a figure on its own terms, from a percentage."""
    if percentage is None:
        return "grey"
    for threshold, color in (
        (90, "brightgreen"),
        (75, "green"),
        (50, "yellow"),
        (25, "orange"),
    ):
        if percentage >= threshold:
            return color
    return "red"


def metric_badge(entry):
    """One metric as a badge: what it reads, and what colour that is worth.

    **The colour is the figure, not the verdict** — with two exceptions. A figure under this
    repository's own minimum is red whatever its value, because falling short of a rule the
    repository wrote down is news; and one nobody could compute, or one taken at another commit, is
    grey, because it is not a figure about this code at all.

    Everywhere else the colour is the absolute number. Painting 32 % green on the grounds that 32 is
    what this repository currently demands would flatter a reader with the project's own floor, and
    a badge exists to be read by somebody who has not opened `ci.yaml`.
    """
    label = entry["metric"]
    if entry["verdict"] == ci_gate.UNMEASURED:
        return label, "not measured", "grey"
    if entry["verdict"] == ci_gate.STALE:
        return label, "stale", "grey"
    if entry["value"] is None:
        return label, "n/a", "grey"
    message = _figure(entry).replace(" %", "%")
    if entry["verdict"] == ci_gate.BELOW:
        return label, message, "red"
    scale = entry["value"] * 10 if entry["unit"] == "score" else entry["value"]
    return label, message, _scale_color(scale)


def badge_name(metric):
    """The file a metric's badge is written to: the dotted name with dots as dashes.

    The same mechanical rule :func:`freeports_dev.ci.report.file_name` uses for the measurement
    files, so a person who knows the metric can find both without a lookup table.
    """
    return metric.replace(".", "-")


def render_badges(model):
    """The badges, as a mapping of filename to content.

    One for the run as a whole, and one for every metric that has something to say — measured, or
    gated, or both. A metric that is neither is left out: a wall of ``n/a`` badges in a README says
    nothing about the repository and hides the ones that do.
    """
    answer = {}
    status = model["status"]
    for name, (label, message, color) in {
        "ci-status": ("ci", status, STATUS_COLORS.get(status, "grey")),
        **{
            badge_name(entry["metric"]): metric_badge(entry)
            for entry in model["metrics"]
            if entry["value"] is not None or entry["minimum"] is not None
        },
    }.items():
        answer[f"{name}.svg"] = _badge_svg(label, message, color)
        answer[f"{name}.json"] = _endpoint(label, message, color)
    return answer


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------

#: The columns whose cells are set as literals, per table. A metric name, a path and a lint rule are
#: all code; a sentence describing what a metric measures is not.
_CODED = {"summary": {0}, "thresholds": {0}, "breakdown": {0, 1}}


def _md_cell(table, index, cell):
    return f"`{cell}`" if index in _CODED[table] and cell != "—" else str(cell)


def _tail_lines(model, table):
    """What goes under every table: why a figure fell short, and what did not hold.

    Only under ``summary``. The other two tables answer a question that has nothing to do with a
    verdict — what is demanded, and where a number comes from — and repeating the failures under
    each of them would make three copies of one list to keep in step.
    """
    if table == "breakdown":
        omitted = breakdown_omitted(model)
        if not omitted:
            return []
        listed = ", ".join(f"{metric} ({count} more)" for metric, count in omitted)
        return [
            f"Only the worst {model['breakdown_limit']} lines of each metric are shown: {listed}. "
            "`freeports-dev ci-report --format json` carries every one of them."
        ]
    if table != "summary":
        return []
    lines = []
    for reason, named in _by_reason(model):
        lines.append(f"{', '.join(named)} — {reason}")
    for condition in failing_conditions(model):
        lines.append(f"{condition['name']} — {condition['detail']}")
    if model["skipped_slow"]:
        lines.append(
            "Skipped, because --skip-slow was given: "
            + ", ".join(model["skipped_slow"])
            + ". Those figures were not checked at all."
        )
    return lines


def render_markdown(model, table=DEFAULT_TABLE):
    spec = TABLES[table]
    rows = list(ROWS[table](model))
    begin, end = MARKERS["markdown"]
    lines = [begin, f"<!-- {WRITTEN_BY} -->", ""]
    if table != DEFAULT_TABLE:
        lines.extend([f"### {spec.heading}", "", spec.prose, ""])
    lines.extend(
        [
            summary(model),
            "",
            f"*{NOTICE}* [{NOTICE_LINK_TEXT}]({GATE_DOC_URL}).",
            "",
            "| " + " | ".join(spec.headers) + " |",
            "| " + " | ".join(spec.alignment) + " |",
        ]
    )
    if rows:
        for row in rows:
            lines.append(
                "| "
                + " | ".join(_md_cell(table, i, c) for i, c in enumerate(row))
                + " |"
            )
    else:
        lines.append("| " + " | ".join("—" for _ in spec.headers) + " |")
    for line in _tail_lines(model, table):
        lines.extend(["", line])
    for state in _legend_states(model) if table == DEFAULT_TABLE else []:
        lines.extend(["", f"*{VERDICT_LABEL[state]}* — {VERDICT_LEGEND[state]}"])
    lines.extend(["", end, ""])
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# reStructuredText
# ---------------------------------------------------------------------------


def _rst_cell(table, index, cell):
    return f"``{cell}``" if index in _CODED[table] and cell != "—" else str(cell)


def _rst_table(headers, rows):
    """A simple table: the rules are as wide as the widest cell in each column."""
    widths = [
        max(len(header), *(len(row[index]) for row in rows))
        for index, header in enumerate(headers)
    ]
    rule = "  ".join("=" * width for width in widths)

    def line(cells):
        return "  ".join(
            cell.ljust(width) for cell, width in zip(cells, widths)
        ).rstrip()

    return [rule, line(headers), rule, *(line(row) for row in rows), rule, ""]


def render_rst(model, table=DEFAULT_TABLE):
    spec = TABLES[table]
    rows = [
        tuple(_rst_cell(table, index, cell) for index, cell in enumerate(row))
        for row in ROWS[table](model)
    ] or [("—",) * len(spec.headers)]

    begin, end = MARKERS["rst"]
    lines = [begin, f".. {WRITTEN_BY}", ""]
    if table != DEFAULT_TABLE:
        lines.extend([f"**{spec.heading}**", "", spec.prose, ""])
    lines.extend(
        [
            summary(model),
            "",
            f"*{NOTICE}*",
            f"`{NOTICE_LINK_TEXT} <{GATE_DOC_URL}>`_.",
            "",
        ]
    )
    lines.extend(_rst_table(spec.headers, rows))
    for line in _tail_lines(model, table):
        lines.extend([line, ""])
    for state in _legend_states(model) if table == DEFAULT_TABLE else []:
        lines.extend([f"*{VERDICT_LABEL[state]}*", f"   {VERDICT_LEGEND[state]}", ""])
    lines.extend([end, ""])
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Putting one where it belongs
# ---------------------------------------------------------------------------


def rewrite(text, block):
    """``text`` with everything between the markers replaced by ``block``.

    The markers are found in ``block`` itself rather than passed separately, so a block can only
    ever be written into a file marked for that same format. Idempotent by construction: what is
    written between the markers includes them, and what is replaced is everything from one to the
    other.
    """
    begin, end = next(
        (pair for pair in MARKERS.values() if block.startswith(pair[0])), (None, None)
    )
    if begin is None:
        raise ValueError("the block carries no markers")

    start = text.find(begin)
    stop = text.find(end, start + len(begin)) if start != -1 else -1
    if start == -1 or stop == -1:
        raise MarkersMissing(
            f"the file carries no {begin} … {end} pair. "
            "Paste both lines where the table should go, and run this again."
        )
    return text[:start] + block.rstrip("\n") + text[stop + len(end) :]


RENDERERS = {
    "json": render_json,
    "html": render_html,
    "markdown": render_markdown,
    "rst": render_rst,
}


def render(model, style, table=DEFAULT_TABLE):
    """One rendering of the model, as text. ``badges`` is not here: it is several files.

    ``--table`` chooses among the three arrangements, and only the two text formats have it.
    ``json`` is the model and a table of it would be a second, lossy one; ``html`` already carries
    all three as tabs, so asking it for one would be asking for a page with two tabs removed. Both
    refuse rather than ignore the argument — silently rendering something other than what was asked
    for is how a hook writes the wrong file for a year.
    """
    if style not in RENDERERS:
        raise KeyError(f"{style} is no rendering; the formats are {', '.join(FORMATS)}")
    if table not in TABLES:
        raise KeyError(f"{table} is no table; the tables are {', '.join(TABLES)}")
    if style not in MARKERS:
        if table != DEFAULT_TABLE:
            raise KeyError(
                f"{style} has no tables; --table is for {', '.join(MARKERS)}"
            )
        return RENDERERS[style](model)
    return RENDERERS[style](model, table)
