# Cleaning, with the GNU standard's four levels rather than one `clean` that means whatever the
# last person needed it to mean.

##@ Cleaning

# `clean` deliberately does not call `cargo clean`: deleting `target/` costs a full recompilation,
# which is not what you want from a target invoked out of habit. That lives in `clean-rust`.
clean: clean-docs ## Build products and debris, without throwing away the cargo cache
	rm -rf $(DISTDIR) build packages/*/build
	rm -rf packages/*/src/*.egg-info packages/*/*.egg-info
	rm -rf .pytest_cache packages/*/.pytest_cache .benchmarks packages/*/.benchmarks .ruff_cache
	find . -name '__pycache__' -type d -not -path './venv/*' -not -path '*/target/*' \
	    -exec rm -rf {} + 2>/dev/null || true
	rm -f freeports.log.jsonl packages/*/freeports.log.jsonl

# `docs/source/_extra/rustdoc` and not `docs/source/_extra`: the latter also holds the validation
# coverage page, which is generated by whoever has the signing keys and committed. Deleting it here
# would make `make clean` a change to the working tree.
clean-docs: ## Only the products of the documentation build
	rm -rf docs/build docs/source/_generated docs/source/_extra/rustdoc

clean-rust: ## cargo clean — the next build will be a full one
	$(CARGO) clean --manifest-path $(MANIFEST)

# The GNU standard's four levels, and what each one costs to undo. `mostlyclean` keeps what is
# expensive to rebuild, which here is the cargo cache: it is what you want between two builds of
# the same tree.
mostlyclean: clean-docs ## Build products, keeping what is expensive to rebuild (the cargo cache)
	rm -rf $(DISTDIR) $(REPORTS)

distclean: clean clean-rust ## clean + clean-rust + removal of the repository's venv
	rm -rf $(REPO_VENV)

# Everything a build can produce, including what only a maintainer can regenerate. The compiled
# translation catalogues are here and not in `clean`: rebuilding them needs the i18n toolchain,
# which a person merely building the site does not have.
maintainer-clean: distclean ## distclean + the generated catalogues (needs the i18n toolchain to undo)
	@echo "This removes files only a maintainer can regenerate."
	rm -rf docs/build docs/source/locales/*/LC_MESSAGES/*.mo
