# Validation: what the methodology grants say, and whether it still holds.
#
# Neither target here can refuse a commit, on any branch, and that is deliberate rather than an
# oversight. A granted reference output regenerated by `make-tests` is ordinary work, and a
# contributor who does not hold the granting key could not clear such a gate at all. What may
# refuse is a *threshold* — `grants.coverage` in `ci.yaml` — and that is `ci-check`'s decision, in
# `mk/ci.mk`, not this file's.

##@ Validation

# What `validation/` claims, written down wherever a reader meets it.
#
# The three badges in README.md, the summary block in it, the seven pages under
# `docs/source/validation/report/` and the single-page HTML rendering are all functions of the same
# thing: the signed documents in `validation/`. A commit that changes a granted file and leaves them
# alone publishes figures that are already wrong, which is why `.githooks/pre-commit` runs this and
# stages what it rewrote.
#
# **One walk of the repository, rendered ten times.** `collect` resolves every methodology page from
# the configured sources; doing it once per artefact would fetch each page ten times over for an
# answer that cannot have changed in between. So the model is collected into a temporary file and
# every rendering is `--model` against it.
#
# The paths below are literal, as they are in a formats repository's hook: where a table belongs in
# a documentation tree is a judgement about that tree, not a setting.
# `--repo` is given outright rather than left to be resolved. A `formats_repo:` line in whatever
# configuration file is found from here outranks "the enclosing Git repository", so a machine
# configured for a formats repository would otherwise have `make validation-report` write this
# repository's README out of somebody else's grants.
#
# The sources are named here for a sharper reason. The grants in `validation/` are made under the
# methodology pages **of this repository**, and the two documentation channels do not carry the same
# text: `latest` is built from this branch and matches `docs/source/validation/` byte for byte,
# `stable` is the last release and lags behind it. `freeports-validate`'s own default is `stable`
# alone, so a run that said nothing would report every grant here as a hash mismatch — an accusation
# produced entirely by reading a different publication of the same page.
#
# Two sources are needed, in this order, and only the command line and a configuration file can
# carry two (`FREEPORTS_VALIDATE_SOURCE` holds exactly one and is never split). A configuration file
# cannot be committed here — every name the engine recognises is gitignored — so the command line it
# is. Override the pair with `make validation-report VALIDATE_SOURCES="<pattern> <pattern>"`; giving
# it empty falls back to whatever your own tiers say.
VALIDATE_SOURCES ?= https://docs.freeports.org/en/latest/_sources/validation/*.rst.txt \
                    https://docs.freeports.org/en/stable/_sources/validation/*.rst.txt
VALIDATE_SOURCE_ARGS = $(foreach source,$(VALIDATE_SOURCES),--source "$(source)")

VALIDATE      = $(ENV_BIN)/freeports-validate$(EXE) --repo "$(CURDIR)" $(VALIDATE_SOURCE_ARGS)
BADGES_DIR    = validation/report/badges
REPORT_DIR    = docs/source/validation/report
# Generated into `_extra/`, which is gitignored and copied verbatim into the root of the site by
# `html_extra_path` — the same arrangement as rustdoc. So it belongs to the *build* and not to the
# commit, and Read the Docs regenerates it in its `pre_build` job.
COVERAGE_HTML = docs/source/_extra/validation/coverage.html
REPORT_TABLES = file-contributor file-methodology contributor-methodology \
                contributor-file methodology-file methodology-contributor

# The three of them, and the name `make ci` calls. All three reach the network, which is why none of
# them is in the commit gate any more and why they are worth having under one name: a person about
# to merge to a production branch runs this once rather than remembering three commands.
#
# `check-grants` is here and is still not a gate. It says whether the claims in `validation/` hold;
# what it says is worth reading and it refuses nothing, on any branch. That rule is unchanged.
validation: validation-report check-grants check-keys ## Everything the grants say, re-established over the network

validation-report: ## Refresh the badges, the README block, the seven doc pages and the HTML
	@model=$$(mktemp) || exit 1; \
	 trap 'rm -f "$$model"' EXIT; \
	 $(VALIDATE) collect > "$$model" || { \
	     echo "freeports-validate: the grants could not be read — nothing was rewritten" >&2; \
	     exit 1; }; \
	 $(VALIDATE) report --model "$$model" --format badges --out $(BADGES_DIR)/; \
	 $(VALIDATE) report --model "$$model" --format markdown --out README.md; \
	 $(VALIDATE) report --model "$$model" --format rst --out $(REPORT_DIR)/index.rst; \
	 for table in $(REPORT_TABLES); do \
	     $(VALIDATE) report --model "$$model" --format rst --table "$$table" \
	         --out "$(REPORT_DIR)/$$table.rst" || exit 1; \
	 done; \
	 mkdir -p $(dir $(COVERAGE_HTML)); \
	 $(VALIDATE) report --model "$$model" --format html --out $(COVERAGE_HTML).new \
	     && mv -f $(COVERAGE_HTML).new $(COVERAGE_HTML) \
	     || { rm -f $(COVERAGE_HTML).new; exit 1; }; \
	 $(FREEPORTS_DEV) ci-record --metric grants.coverage --from validate --input "$$model"

# `grants.coverage` is measured out of that same model, as one more rendering of the walk that has
# already happened. It is the last line of the recipe rather than a target of its own for exactly
# that reason: collecting a second time would re-resolve every methodology page over the network
# for an answer that cannot have changed in between.
#
# It also has to happen *here*, in the recipe that runs at every commit. A figure recorded by a
# command nobody runs regularly goes stale, and `ci-check` then refuses on a production branch for
# a reason that has nothing to do with the commit being made — which is precisely what happened the
# first time this was wired, when nothing in the Makefile re-measured it at all.

# The integrity check itself: signatures verify, hashes still match, methodology pages still say
# what they said. It is *not* a lint — a passing run says the claims in `validation/` hold, not that
# the software is correct — and it needs no signing key to check somebody else's document.
check-grants: ## Verify every claim made in validation/
	$(VALIDATE) check-grants


# Whether the granters' keys are published where a stranger can fetch them.
#
# A signature checks out against a keyring, which answers "was this signed by the key it names". It
# does not answer "can anybody else get that key" — and if they cannot, the signature is checkable
# only by people who already have it, which is everybody except the person a published grant exists
# to convince.
#
# Its own target, and **not** part of `ci-fast`: it reaches a key server over the network, and a
# commit on a dev branch must not depend on somebody else's host being up. `make ci` runs it, and
# each repository's hook runs it on a prod branch only.
#
# A key that could not be looked up makes the metric *unmeasured* rather than lowering it. Reporting
# "I could not reach the server" as a number would turn a fact about the network into a fact about
# the repository.
check-keys: ## Whether the granters' keys are published on the configured key server
	@keys=$$(mktemp) || exit 1; \
	 trap 'rm -f "$$keys"' EXIT; \
	 $(VALIDATE) check-keys | tee "$$keys"; \
	 $(FREEPORTS_DEV) ci-record --metric grants.keys_online --from check-keys --input "$$keys"
