# Validation: what the methodology grants say, and whether it still holds.
#
# Nothing in this file can refuse a commit, on any branch, and that is deliberate rather than an
# oversight. A granted reference output regenerated by `make-tests` is ordinary work, and a
# contributor who does not hold the granting key could not clear such a gate at all. What may
# refuse is a *threshold* — `grants.coverage` and `grants.keys_online` in `ci.yaml` — and that is
# `ci-check`'s decision, in `mk/ci.mk`, not this file's.

##@ Validation

# What `validation/` claims, written down wherever a reader meets it.
#
# The three badges in README.md, the summary block in it, the seven pages under
# `docs/source/validation/report/` and the single-page HTML rendering are all functions of the same
# thing: the signed documents in `validation/`. A commit that changes a granted file and leaves them
# alone publishes figures that are already wrong, which is why `.githooks/pre-commit` runs this and
# stages what it rewrote.
#
# **One walk of the repository, rendered ten times.** `collect` resolves every methodology page from
# the configured sources; doing it once per artefact would fetch each page ten times over for an
# answer that cannot have changed in between. So the model is collected into a temporary file and
# every rendering is `--model` against it.
#
# The paths below are literal, as they are in a formats repository's hook: where a table belongs in
# a documentation tree is a judgement about that tree, not a setting.
# `--repo` is given outright rather than left to be resolved. A `formats_repo:` line in whatever
# configuration file is found from here outranks "the enclosing Git repository", so a machine
# configured for a formats repository would otherwise have `make validation-report` write this
# repository's README out of somebody else's grants.
#
# The sources are **not** named here, and that is the setting rather than an omission.
#
# `freeports-validate`'s own default is the published `stable` channel, and it is the right default
# everywhere: `stable` is the last release, it is what a reader can fetch, and a grant is a claim
# addressed to that reader. A pattern written down in this file would outrank a configuration
# file — the command line always does — and would therefore take a decision away from whoever is
# running it, silently.
#
# The decision it would take is a real one. `latest` is built from this branch and matches
# `docs/source/validation/` byte for byte; `stable` lags behind it. Somebody working on a
# methodology page needs `latest` to see their own grants resolve, and that belongs in the tier
# where a personal choice belongs:
#
#     validate:                                    # in your own freeports-conf.yaml
#       sources:
#         - https://docs.freeports.org/en/latest/_sources/validation/*.rst.txt
#         - https://docs.freeports.org/en/stable/_sources/validation/*.rst.txt
#
# `freeports-validate sources` prints what is in force. For a one-off, this variable still works:
# `make validation-report VALIDATE_SOURCES="<pattern> <pattern>"`.
VALIDATE_SOURCES ?=
VALIDATE_SOURCE_ARGS = $(foreach source,$(VALIDATE_SOURCES),--source "$(source)")

VALIDATE      = $(ENV_BIN)/freeports-validate$(EXE) --repo "$(CURDIR)" $(VALIDATE_SOURCE_ARGS)
BADGES_DIR    = validation/report/badges
REPORT_DIR    = docs/source/validation/report
# Generated into `_extra/`, which is gitignored and copied verbatim into the root of the site by
# `html_extra_path` — the same arrangement as rustdoc. So it belongs to the *build* and not to the
# commit, and Read the Docs regenerates it in its `pre_build` job.
COVERAGE_HTML = docs/source/_extra/validation/coverage.html
REPORT_TABLES = file-contributor file-methodology contributor-methodology \
                contributor-file methodology-file methodology-contributor

# The three of them, and the name `make ci` calls. All three reach the network, which is why none of
# them is in the commit gate any more and why they are worth having under one name: a person about
# to merge to a production branch runs this once rather than remembering three commands.
#
# `check-grants` is here and is still not a gate. It says whether the claims in `validation/` hold;
# what it says is worth reading and it refuses nothing, on any branch. That rule is unchanged.
validation: validation-report check-grants check-keys ## Everything the grants say, re-established over the network

# **A walk that resolved nothing is not a walk whose answer may be published.** `collect` exits 0
# whether or not the methodology pages came back — establishing what it could establish is its whole
# job — but every rendering below is *committed*, so writing one out of a walk that reached nothing
# would replace a report saying "coverage 100 %, check-grants passing" with one saying "coverage --,
# failing". That difference is a fact about somebody's web server, not about this repository, and it
# is the rule this project already holds for a page it could not reach: unverifiable is not granted,
# and it must not be published as ungranted either.
#
# So the figure is recorded first, out of the same model, and read back. `unmeasured` means nothing
# resolved, and then nothing is rewritten and the reason is printed loudly. The metric stays
# unmeasured, `ci-check` reports it as such, and on a production branch that threshold refuses —
# which is the correct outcome, and the only way anything here bears on a commit: a production commit
# whose grants nobody could check is not one that may be made.
#
# Nothing in the recipe exits non-zero, for the reason the header gives. A report one run out of date
# is a smaller problem than a commit that cannot be made, and the unmeasured figure says so anyway.
validation-report: ## Refresh the badges, the README block, the seven doc pages and the HTML
	@model=$$(mktemp) || exit 1; \
	 trap 'rm -f "$$model"' EXIT; \
	 if ! $(VALIDATE) collect > "$$model" || [ ! -s "$$model" ]; then \
	     echo "freeports-validate: the grants could not be read — nothing was rewritten" >&2; \
	     exit 0; \
	 fi; \
	 $(FREEPORTS_DEV) ci-record --metric grants.coverage --from validate --input "$$model" \
	     >/dev/null 2>&1; \
	 if grep -q '"state": *"unmeasured"' "$(REPORTS)/grants-coverage.json" 2>/dev/null; then \
	     echo "freeports-validate: no methodology page could be resolved, so the report is" >&2; \
	     echo "unchanged. It is not being rewritten to say the grants failed: that would be a" >&2; \
	     echo "claim about the network. \`freeports-validate sources\` says where pages are" >&2; \
	     echo "fetched from and what each name resolves to." >&2; \
	     exit 0; \
	 fi; \
	 $(VALIDATE) report --model "$$model" --format badges --out $(BADGES_DIR)/; \
	 $(VALIDATE) report --model "$$model" --format markdown --out README.md; \
	 $(VALIDATE) report --model "$$model" --format rst --out $(REPORT_DIR)/index.rst; \
	 for table in $(REPORT_TABLES); do \
	     $(VALIDATE) report --model "$$model" --format rst --table "$$table" \
	         --out "$(REPORT_DIR)/$$table.rst" || exit 0; \
	 done; \
	 mkdir -p $(dir $(COVERAGE_HTML)); \
	 $(VALIDATE) report --model "$$model" --format html --out $(COVERAGE_HTML).new \
	     && mv -f $(COVERAGE_HTML).new $(COVERAGE_HTML) \
	     || rm -f $(COVERAGE_HTML).new

# `grants.coverage` is measured out of that same model rather than by a target of its own:
# collecting a second time would re-resolve every methodology page over the network for an answer
# that cannot have changed in between. It is now the *first* thing the recipe does with the model
# rather than the last, because it is what decides whether the renderings may be published at all.
#
# It also has to happen *here*, in the recipe that runs at every commit. A figure recorded by a
# command nobody runs regularly goes stale, and `ci-check` then refuses on a production branch for
# a reason that has nothing to do with the commit being made — which is precisely what happened the
# first time this was wired, when nothing in the Makefile re-measured it at all.

# The integrity check itself: signatures verify, hashes still match, methodology pages still say
# what they said. It is *not* a lint — a passing run says the claims in `validation/` hold, not that
# the software is correct — and it needs no signing key to check somebody else's document.
#
# **It never refuses a commit, on any branch, and that includes this repository.** It used to: `ci`
# depends on `validation`, a failing recipe fails the make, and the hook refuses on a failing make —
# so a production commit here was refused over a grant, which is exactly what every other repository
# and every page of the documentation says does not happen. The reasoning is the workspace's, not
# the formats side's: a granted reference output regenerated by `make-tests` is ordinary work, and a
# contributor who does not hold the granting key could not clear such a gate at all.
#
# What may refuse on a production branch is a **threshold**, and only that: `grants.coverage` under
# its minimum, and `grants.keys_online` under its own — a granter's key that cannot be fetched from
# the key server makes the signature checkable only by people who already have it, which is
# everybody except the reader a published grant exists to convince. Files being vouched for is not
# the gate; enough of them being vouched for, by keys somebody else can download, is.
#
# `GATE` is what expresses it, the same variable the two gates set and every prerequisite inherits.
# Reached from `ci-fast` or `ci-full` the failure is reported and the run continues to the verdict;
# `make check-grants` typed on its own still fails, because a command asked a question must answer
# it in its exit status.
check-grants: ## Verify every claim made in validation/
	@$(VALIDATE) check-grants || { \
	    echo "" >&2; \
	    echo "freeports-validate: the grants above are not all vouched for by this run." >&2; \
	    echo "The commit is not being refused — grant integrity never refuses, on any branch." >&2; \
	    echo "Re-grant with \`freeports-validate grant\`, or restate a changed one with" >&2; \
	    echo "\`freeports-validate update\`, once you know which it is." >&2; \
	    test -n "$(GATE)"; }


# Whether the granters' keys are published where a stranger can fetch them.
#
# A signature checks out against a keyring, which answers "was this signed by the key it names". It
# does not answer "can anybody else get that key" — and if they cannot, the signature is checkable
# only by people who already have it, which is everybody except the person a published grant exists
# to convince.
#
# Its own target, and **not** part of `ci-fast`: it reaches a key server over the network, and a
# commit on a dev branch must not depend on somebody else's host being up. `make ci` runs it, and
# each repository's hook runs it on a prod branch only.
#
# A key that could not be looked up makes the metric *unmeasured* rather than lowering it. Reporting
# "I could not reach the server" as a number would turn a fact about the network into a fact about
# the repository.
check-keys: ## Whether the granters' keys are published on the configured key server
	@keys=$$(mktemp) || exit 1; \
	 trap 'rm -f "$$keys"' EXIT; \
	 $(VALIDATE) check-keys | tee "$$keys"; \
	 $(FREEPORTS_DEV) ci-record --metric grants.keys_online --from check-keys --input "$$keys"
