#!/usr/bin/env python3
"""Turning the collected model into something a person or a README can read.

`bin/collect` establishes the facts -- it walks the validation documents, resolves each methodology
from the configured sources, hashes what it finds and compares. This renders them, and does nothing
else. That is the split the whole command follows: **bash establishes facts, Python parses and
renders**, so everything that decides something about trust stays a shell command a user can retype.

Every rendering here is a pure function of the model, which is why the model exists at all::

    $ freeports-validate report --format json | jq '.grants[] | select(.state != "current")'
    $ freeports-validate report --format html     --out coverage.html
    $ freeports-validate report --format badges   --out docs/badges/
    $ freeports-validate report --format markdown --out README.md
    $ freeports-validate report --format markdown --table methodology-file --out covered.md

The first of those answers questions no rendering here anticipated, and it stays available however
the others change. Run by hand, this script reads the model on standard input::

    $ freeports-validate collect | python3 report.py html --out coverage.html

The three viewpoints of the HTML page are the command's three lookup subcommands -- `who-grants`
(by file), `granted-by` (by contributor), `granted-with` (by methodology). A reader who has learned
one has learned the page, and a page that invented a fourth arrangement would be teaching a second
vocabulary for the same repository.

The two text formats take the same three viewpoints one at a time, through `--table`, and in both
of each one's groupings -- six arrangements plus the summary, listed in `TABLES`. A page cannot
carry tabs, so where the HTML shows three panels a repository keeps six files, one per arrangement,
each saying in its heading which invocation it is the written-down form of.

**Nothing here carries a timestamp.** A report is a function of the repository, and a date stamped
into it would make the Markdown rewriting differ from itself on every run -- a diff in every commit
saying nothing had changed. What a reader wants to know is what the repository says now, which is
what running the command again tells them.
"""

import html
import json
import os
import sys


#: What a rendering may be asked for. `json` is the model itself, and is first because it is the
#: one that outlives this file: a question none of the others answers is a `jq` expression away.
FORMATS = ("json", "html", "badges", "markdown", "rst")

#: The lines a rewritable file must already contain, per format. They are ordinary comments in both
#: languages, so a file carrying them renders exactly as it did before anything was written between
#: them.
MARKERS = {
    "markdown": (
        "<!-- freeports-validate:begin -->",
        "<!-- freeports-validate:end -->",
    ),
    "rst": (".. freeports-validate:begin", ".. freeports-validate:end"),
}

#: Where a reader goes to find out what any of this is worth. The published documentation, not the
#: source a run happened to resolve: the human page is the one that explains the mechanism, and a
#: reader following this link is asking what a grant *means*, not what its bytes hashed to.
GENERAL_METHODOLOGY_URL = (
    "https://docs.freeports.org/en/stable/validation/general_methodology.html"
)

#: The sentence every rendering carries, and the reason it is not optional.
#:
#: A page of green ticks and a percentage invites exactly one misreading -- that somebody has
#: certified the data -- and that is the misreading this whole mechanism exists to prevent. What a
#: report actually shows is what the validation documents in a repository *say*, as of one run, on
#: one machine, against whatever sources that machine had configured. It is evidence a reader can
#: reproduce, not a guarantee anybody is offering, and the only way to be sure of a line in it is to
#: run the command and watch it check.
#:
#: Kept to two sentences and a link on purpose. A caveat that dominates the page would be its own
#: kind of dishonesty -- the report is genuinely useful, and burying it under warnings would say it
#: is not.
NOTICE = (
    "Generated by `freeports-validate report`, and demonstrative: it shows what this "
    "repository's validation documents claim as of one run, not that the data is correct. "
    "To be sure of any line, run `freeports-validate check-grants` yourself."
)

NOTICE_LINK_TEXT = "What these claims are worth: the general methodology"

#: The two marks a grant can carry, spelled out once and used by every rendering.
#:
#: They are the marks the three lookup subcommands already print, with the same wording, because a
#: reader who learned `(!)` from `granted-by` has learned it here too. Kept apart on purpose:
#: `(!)` is an answer -- the methodology says it does not cover this -- and `(?)` is the absence of
#: one, and reading the second as the first would accuse a granter over a network failure.
OUT_OF_SCOPE_LEGEND = (
    "(!) granted outside the paths its methodology declares it supports."
)
UNRESOLVED_LEGEND = "(?) the methodology page could not be resolved, so the question could not be asked."

#: Shields' own palette, so a badge generated here sits beside a badge fetched from shields.io
#: without the two looking like they came from different projects.
COLORS = {
    "brightgreen": "#4c1",
    "green": "#97ca00",
    "yellow": "#dfb317",
    "orange": "#fe7d37",
    "red": "#e05d44",
    "blue": "#007ec6",
    "grey": "#9f9f9f",
}

#: What the one-word status of a run is worth on a badge. `inconclusive` is grey rather than red on
#: purpose: a methodology that could not be reached has disproved nothing, and colouring it as a
#: failure would make a train journey look like a broken repository.
STATUS_COLORS = {
    "passing": "brightgreen",
    "failing": "red",
    "inconclusive": "grey",
}


class MarkersMissing(Exception):
    """A file to be rewritten does not say where the report goes.

    Deliberately not "append it at the end". Where a coverage table belongs in a README is a
    judgement about that README, and a command that guessed would put a table under a licence
    notice once and then keep it there for ever.
    """


# ---------------------------------------------------------------------------
# Reading the model
# ---------------------------------------------------------------------------


def _percentage(coverage):
    """A coverage figure as a percentage, or ``None`` when there is no denominator.

    A methodology that declares no paths has nothing it could be complete against, so it has no
    ratio -- and the honest rendering of that is a word, never a zero. Zero would say every file it
    could cover is uncovered, which is the opposite of what is known.
    """
    if not coverage or coverage.get("ratio") is None:
        return None
    return round(coverage["ratio"] * 100)


def _coverage_text(coverage):
    """``2/4 (50%)``, or the dash that means there is no such fraction."""
    percentage = _percentage(coverage)
    if percentage is None:
        return "--"
    return f"{coverage['granted']}/{coverage['candidates']} ({percentage}%)"


def _plural(count, singular, plural):
    """``1 grant`` / ``2 grants``, written out rather than parenthesised.

    ``grant(s)`` costs nothing to produce and makes every sentence in the report slightly harder to
    read than it needs to be, in a document whose whole purpose is to be read.
    """
    return f"{count} {singular if count == 1 else plural}"


def _summary(model):
    """The one sentence every rendering opens with."""
    totals = model["totals"]
    return (
        f"{_plural(totals['grants'], 'grant', 'grants')} by "
        f"{_plural(totals['contributors'], 'contributor', 'contributors')} under "
        f"{_plural(totals['methodologies'], 'methodology', 'methodologies')}; "
        f"coverage {_coverage_text(model['coverage'])}; "
        f"check-grants: {model['status']}"
    )


def _scope_mark(grant):
    """The mark the three lookup subcommands already use, for the same fact.

    ``None`` is not ``False``: a page that could not be resolved leaves the question unasked, and
    accusing a granter over a network failure is the one answer that is certainly wrong.
    """
    if grant.get("in_scope") is False:
        return " (!)"
    if grant.get("in_scope") is None:
        return " (?)"
    return ""


# ---------------------------------------------------------------------------
# JSON
# ---------------------------------------------------------------------------


def render_json(model):
    return json.dumps(model, indent=2, sort_keys=False) + "\n"


# ---------------------------------------------------------------------------
# HTML
# ---------------------------------------------------------------------------

#: Everything the page needs to look like a page. Inline, and it has to stay inline: a coverage
#: report that went to a content delivery network for its stylesheet would render as unformatted
#: text on exactly the machines -- an air-gapped build, an auditor's laptop on a train -- this
#: command already goes out of its way to work on.
STYLE = """
:root { color-scheme: light dark; --line: #d4d4d4; --muted: #6b6b6b;
        --ok: #1a7f37; --bad: #b42318; --unsure: #8a6d1f; }
@media (prefers-color-scheme: dark) {
  :root { --line: #3a3a3a; --muted: #9a9a9a;
          --ok: #4ac26b; --bad: #ff6a5e; --unsure: #d4a72c; } }
body { font: 15px/1.5 system-ui, sans-serif; margin: 0 auto; max-width: 62rem; padding: 2rem 1rem; }
h1 { font-size: 1.4rem; margin: 0 0 .25rem; }
p.summary { color: var(--muted); margin: 0 0 .75rem; }
p.notice { border-left: 3px solid var(--line); color: var(--muted); font-size: .88rem;
           margin: 0 0 1.5rem; padding: .1rem 0 .1rem .7rem; }
nav { border-bottom: 1px solid var(--line); display: flex; gap: .25rem; margin-bottom: 1rem; }
nav button { background: none; border: 0; border-bottom: 2px solid transparent; color: inherit;
             cursor: pointer; font: inherit; padding: .5rem .9rem; }
nav button[aria-selected="true"] { border-bottom-color: currentColor; font-weight: 600; }
input[type="search"] { border: 1px solid var(--line); border-radius: .3rem; font: inherit;
                       margin-bottom: 1rem; padding: .4rem .6rem; width: 100%; }
table { border-collapse: collapse; font-size: .92rem; width: 100%; }
th, td { border-bottom: 1px solid var(--line); padding: .4rem .5rem; text-align: left;
         vertical-align: top; }
th { font-weight: 600; }
td.n { text-align: right; }
code { font-size: .9em; overflow-wrap: anywhere; }
.state-current { color: var(--ok); }
.state-changed, .state-missing { color: var(--bad); }
.state-unknown, .state-unreachable, .state-unresolved { color: var(--unsure); }
.prose { color: var(--muted); margin: .2rem 0 0; }
.legend { color: var(--muted); font-size: .85rem; margin-top: 2rem; }
[hidden] { display: none !important; }
"""

#: The only behaviour the page has: switching viewpoint, and filtering rows by substring. Written
#: out rather than pulled from a framework for the same reason as the stylesheet, and kept small
#: enough to read in one screen -- a reader auditing a repository should be able to satisfy
#: themselves that the page does not do anything else.
SCRIPT = """
const tabs = document.querySelectorAll('nav button');
const panels = document.querySelectorAll('section[data-panel]');
tabs.forEach(function (tab) {
  tab.addEventListener('click', function () {
    tabs.forEach(function (other) {
      other.setAttribute('aria-selected', String(other === tab));
    });
    panels.forEach(function (panel) {
      panel.hidden = panel.dataset.panel !== tab.dataset.tab;
    });
  });
});
document.querySelector('input[type="search"]').addEventListener('input', function (event) {
  const needle = event.target.value.toLowerCase();
  document.querySelectorAll('tbody tr').forEach(function (row) {
    row.hidden = needle !== '' && !row.textContent.toLowerCase().includes(needle);
  });
});
"""

VIEWPOINTS = (
    ("files", "By file"),
    ("contributors", "By contributor"),
    ("methodologies", "By methodology"),
)


def _e(value):
    """Escaped, and ``None`` rendered as the dash that means "nothing to say here"."""
    return html.escape("--" if value is None else str(value))


def _state(value):
    return f'<span class="state-{_e(value)}">{_e(value)}</span>'


def _link(uri, text):
    """A link to the text a methodology resolved from, or the text alone when there is none.

    This is the one outward reference the page makes, and it is a link rather than a fetch: the
    reader decides whether to follow it, and the page renders the same with or without a network.
    """
    if not uri:
        return _e(text)
    return f'<a href="{_e(uri)}">{_e(text)}</a>'


def _table(headers, rows):
    head = "".join(f"<th>{_e(header)}</th>" for header in headers)
    body = "\n".join("<tr>" + "".join(row) + "</tr>" for row in rows)
    if not rows:
        body = f'<tr><td colspan="{len(headers)}">Nothing to report yet.</td></tr>'
    return f"<table><thead><tr>{head}</tr></thead><tbody>\n{body}\n</tbody></table>"


def _files_panel(model):
    rows = [
        [
            f"<td><code>{_e(grant['path'])}</code>{_e(_scope_mark(grant))}</td>",
            f"<td>{_e(grant['methodology'])}</td>",
            f"<td>{_e(grant['contributor'])}</td>",
            f"<td>{_state(grant['state'])}</td>",
        ]
        for grant in model["grants"]
    ]
    return _table(("File", "Methodology", "Granted by", "State"), rows)


def _contributors_panel(model):
    rows = [
        [
            f"<td>{_e(person['name'])}</td>",
            f"<td><code>{_e(person['email'])}</code></td>",
            f"<td>{_e(', '.join(person['methodologies']))}</td>",
            f'<td class="n">{_e(person["grants"])}</td>',
            f"<td>{_state(person['signature'])}</td>",
            f"<td>{_state(person['version'])}</td>",
        ]
        for person in model["contributors"]
    ]
    return _table(
        ("Contributor", "Email", "Methodologies", "Grants", "Signature", "Version"),
        rows,
    )


def _methodologies_panel(model):
    rows = []
    for methodology in model["methodologies"]:
        patterns = "".join(
            f'<p class="prose"><code>{_e(entry["pattern"])}</code> — '
            f"{_e(entry['prose'])}</p>"
            for entry in methodology["patterns"]
        )
        if methodology["declares_paths"] is False:
            patterns = (
                '<p class="prose">Declares no paths, so it covers any of them '
                "and has no coverage figure.</p>"
            )
        rows.append(
            [
                f"<td>{_link(methodology['uri'], methodology['name'])}{patterns}</td>",
                f"<td>{_state(methodology['state'])}</td>",
                f"<td>{_e(', '.join(sorted({a['contributor'] for a in methodology['adoptions']})))}</td>",
                f'<td class="n">{_e(methodology["grants"])}</td>',
                f'<td class="n">{_e(_coverage_text(methodology["coverage"]))}</td>',
            ]
        )
    return _table(("Methodology", "State", "Adopted by", "Grants", "Coverage"), rows)


def render_html(model):
    panels = {
        "files": _files_panel(model),
        "contributors": _contributors_panel(model),
        "methodologies": _methodologies_panel(model),
    }
    tabs = "".join(
        f'<button data-tab="{key}" aria-selected="{str(index == 0).lower()}">'
        f"{_e(label)}</button>"
        for index, (key, label) in enumerate(VIEWPOINTS)
    )
    sections = "\n".join(
        f'<section data-panel="{key}"{"" if index == 0 else " hidden"}>'
        f"{panels[key]}</section>"
        for index, (key, _label) in enumerate(VIEWPOINTS)
    )
    sources = "".join(
        f"<li><code>{_e(source)}</code></li>" for source in model["sources"]
    )
    name = model.get("repository", {}).get("name") or "this repository"
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Validation coverage — {_e(name)}</title>
<style>{STYLE}</style>
</head>
<body>
<h1>Validation coverage — {_e(name)}</h1>
<p class="summary">{_e(_summary(model))}</p>
<p class="notice">{_e(NOTICE)}
<a href="{_e(GENERAL_METHODOLOGY_URL)}">{_e(NOTICE_LINK_TEXT)}</a>.</p>
<nav>{tabs}</nav>
<input type="search" placeholder="Filter rows…" aria-label="Filter rows">
{sections}
<p class="legend">{OUT_OF_SCOPE_LEGEND}
{UNRESOLVED_LEGEND}</p>
<div class="legend">Methodologies resolved from:<ul>{sources}</ul></div>
<script>{SCRIPT}</script>
</body>
</html>
"""


# ---------------------------------------------------------------------------
# Badges
# ---------------------------------------------------------------------------

#: Verdana at 11px, which is what shields measures against. An approximation is good enough here:
#: the consequence of being a pixel out is a badge with slightly wide padding, and the alternative
#: is shipping a font metrics table for three short strings.
_CHARACTER_WIDTH = 7.0
_SIDE_PADDING = 10.0


def _badge_svg(label, message, color):
    """One shields-style badge, drawn here rather than fetched.

    Drawn locally so that generating a report needs no network either: a command that fetched its
    own badges would make `--format badges` fail in the same places `--offline` exists for.
    """
    label_width = _CHARACTER_WIDTH * len(label) + _SIDE_PADDING * 2
    message_width = _CHARACTER_WIDTH * len(message) + _SIDE_PADDING * 2
    total = label_width + message_width
    label_middle = label_width / 2
    message_middle = label_width + message_width / 2
    fill = COLORS.get(color, COLORS["grey"])
    title = html.escape(f"{label}: {message}")
    label = html.escape(label)
    message = html.escape(message)
    return f"""<svg xmlns="http://www.w3.org/2000/svg" \
width="{total:.0f}" height="20" role="img" aria-label="{title}">
<title>{title}</title>
<linearGradient id="gradient" x2="0" y2="100%">
<stop offset="0" stop-color="#bbb" stop-opacity=".1"/>
<stop offset="1" stop-opacity=".1"/>
</linearGradient>
<clipPath id="rounded"><rect width="{total:.0f}" height="20" rx="3" fill="#fff"/></clipPath>
<g clip-path="url(#rounded)">
<rect width="{label_width:.0f}" height="20" fill="#555"/>
<rect x="{label_width:.0f}" width="{message_width:.0f}" height="20" fill="{fill}"/>
<rect width="{total:.0f}" height="20" fill="url(#gradient)"/>
</g>
<g fill="#fff" text-anchor="middle" font-family="Verdana,DejaVu Sans,sans-serif" font-size="11">
<text x="{label_middle:.0f}" y="15" fill="#010101" fill-opacity=".3">{label}</text>
<text x="{label_middle:.0f}" y="14">{label}</text>
<text x="{message_middle:.0f}" y="15" fill="#010101" fill-opacity=".3">{message}</text>
<text x="{message_middle:.0f}" y="14">{message}</text>
</g>
</svg>
"""


def _endpoint(label, message, color):
    """The same badge as data, for anyone who would rather shields.io drew it."""
    return (
        json.dumps(
            {
                "schemaVersion": 1,
                "label": label,
                "message": message,
                "color": color,
            },
            indent=2,
        )
        + "\n"
    )


def _coverage_color(percentage):
    if percentage is None:
        return "grey"
    for threshold, color in (
        (90, "brightgreen"),
        (75, "green"),
        (50, "yellow"),
        (25, "orange"),
    ):
        if percentage >= threshold:
            return color
    return "red"


def render_badges(model):
    """The three badges, as a mapping of filename to content.

    Three because they are the three questions a README is asked: how much has been vouched for, how
    much of what could be, and does it all still hold.
    """
    percentage = _percentage(model["coverage"])
    badges = {
        "grants-total": ("grants", str(model["totals"]["grants"]), "blue"),
        "grants-coverage": (
            "coverage",
            "n/a" if percentage is None else f"{percentage}%",
            _coverage_color(percentage),
        ),
        "check-grants": (
            "check-grants",
            model["status"],
            STATUS_COLORS.get(model["status"], "grey"),
        ),
    }
    answer = {}
    for name, (label, message, color) in badges.items():
        answer[f"{name}.svg"] = _badge_svg(label, message, color)
        answer[f"{name}.json"] = _endpoint(label, message, color)
    return answer


# ---------------------------------------------------------------------------
# Markdown and reStructuredText
# ---------------------------------------------------------------------------

WRITTEN_BY = (
    "Written by `freeports-validate report`. Anything between the markers is replaced."
)


class Table:
    """One arrangement of the same repository: what it groups by, and what it lists.

    The repository has three dimensions -- file, contributor, methodology -- and a lookup is a
    choice of two of them: group by the first, list the second. Taken in every order that is six
    tables, which is exactly what the three lookup subcommands are with and without their flag. The
    name of each reads as *grouped by the first, listing the second*; `mirrors` says which
    invocation it is the written-down form of, so nobody has to learn a second vocabulary for a
    repository they can already ask about on the command line.

    `group` and `listed` are keys of a grant in the model, not display words: the whole table is
    built by reading those two fields off every grant, which is why adding a seventh arrangement
    would be a line of data rather than a function.
    """

    #: Which key of a grant each dimension is, and how a value of it is written in a table cell.
    #: A path is code and is set in a literal; a methodology is a document and is linked to the text
    #: it resolved from; a person is a name and is left alone.
    DIMENSIONS = {
        "file": "path",
        "contributor": "contributor",
        "methodology": "methodology",
    }

    def __init__(self, group, listed, heading, mirrors, headers):
        self.group = group
        self.listed = listed
        self.heading = heading
        self.mirrors = mirrors
        self.headers = headers


#: The seven values of `--table`. `summary` is first because it is the default and the one the
#: renderings have always had; the six after it are in the order the three lookup subcommands come
#: in, each immediately followed by its flag.
TABLES = {
    "summary": Table(
        None,
        None,
        "Coverage by methodology",
        None,
        ("Methodology", "Grants", "Coverage", "Adopted by"),
    ),
    "file-contributor": Table(
        "file",
        "contributor",
        "By file, listing who vouched for it",
        "who-grants <file>",
        ("File", "Granted by", "State"),
    ),
    "file-methodology": Table(
        "file",
        "methodology",
        "By file, listing the methodologies it was granted under",
        "who-grants -m <file>",
        ("File", "Methodology", "State"),
    ),
    "contributor-methodology": Table(
        "contributor",
        "methodology",
        "By contributor, listing the methodologies they used",
        "granted-by <contributor>",
        ("Contributor", "Methodology", "State"),
    ),
    "contributor-file": Table(
        "contributor",
        "file",
        "By contributor, listing the files they vouched for",
        "granted-by -f <contributor>",
        ("Contributor", "File", "State"),
    ),
    "methodology-file": Table(
        "methodology",
        "file",
        "By methodology, listing the files it covers",
        "granted-with <methodology>",
        ("Methodology", "File", "State"),
    ),
    "methodology-contributor": Table(
        "methodology",
        "contributor",
        "By methodology, listing who adopted it",
        "granted-with -c <methodology>",
        ("Methodology", "Contributor", "State"),
    ),
}

#: The default, and the one every earlier caller of `render` is asking for without saying so.
DEFAULT_TABLE = "summary"


def _uri_of(model, name):
    """Where a methodology resolved from, or ``None`` when nothing could be resolved."""
    return next(
        (entry["uri"] for entry in model["methodologies"] if entry["name"] == name),
        None,
    )


def _mark_of(scopes):
    """The mark a pair of dimensions carries, given every `in_scope` its grants reported.

    A refusal outranks an unasked question. A pair holding both has been told by the methodology
    that it does not cover this, and one document failing to resolve the page afterwards does not
    unsay it.
    """
    if False in scopes:
        return " (!)"
    if None in scopes:
        return " (?)"
    return ""


def _pairs(model, table):
    """Every distinct (group, listed) pair in the grants, with its states and its mark.

    One row per pair rather than one per grant: the same file granted under the same methodology by
    two contributors' documents is one claim about that pair, and printing it twice would make a
    table disagree with the lookup subcommand it mirrors. The states of the grants behind it are
    kept -- almost always one word, and two when two documents disagree about the file, which is
    the case a reader most needs to see.
    """
    group_key = Table.DIMENSIONS[table.group]
    listed_key = Table.DIMENSIONS[table.listed]
    found = {}
    for grant in model["grants"]:
        key = (grant[group_key], grant[listed_key])
        states, scopes = found.setdefault(key, (set(), set()))
        states.add(grant["state"])
        scopes.add(grant.get("in_scope"))
    for (group, listed), (states, scopes) in sorted(found.items()):
        yield group, listed, ", ".join(sorted(states)), _mark_of(scopes)


def _legends(model, table):
    """The legend lines a table needs, and only those.

    Printed under the table and only when a mark is actually on it: a file kept under version
    control gains nothing from an explanation of a symbol it does not contain, and the next reader
    would have to check whether it was stale.
    """
    marks = {mark for _group, _listed, _states, mark in _pairs(model, table)}
    lines = []
    if " (!)" in marks:
        lines.append(OUT_OF_SCOPE_LEGEND)
    if " (?)" in marks:
        lines.append(UNRESOLVED_LEGEND)
    return lines


# ---------------------------------------------------------------------------
# Markdown
# ---------------------------------------------------------------------------


def _md_cell(model, dimension, value, mark=""):
    if dimension == "file":
        return f"`{value}`{mark}"
    if dimension == "methodology":
        uri = _uri_of(model, value)
        return f"[{value}]({uri}){mark}" if uri else f"{value}{mark}"
    return f"{value}{mark}"


def _md_summary_rows(model):
    for methodology in model["methodologies"]:
        yield (
            _md_cell(model, "methodology", methodology["name"]),
            str(methodology["grants"]),
            _coverage_text(methodology["coverage"]),
            ", ".join(sorted({a["contributor"] for a in methodology["adoptions"]})),
        )


def _md_pair_rows(model, table):
    for group, listed, states, mark in _pairs(model, table):
        yield (
            _md_cell(model, table.group, group),
            _md_cell(model, table.listed, listed, mark),
            states,
        )


#: How the summary's four columns are aligned. The two numeric ones are set right, which is the one
#: thing a Markdown table can do to make figures comparable down a column.
SUMMARY_ALIGNMENT = ("---", "---:", "---:", "---")


def render_markdown(model, table=DEFAULT_TABLE):
    spec = TABLES[table]
    if table == DEFAULT_TABLE:
        rows = list(_md_summary_rows(model))
        alignment = SUMMARY_ALIGNMENT
        empty = ("—",) * len(spec.headers)
    else:
        rows = list(_md_pair_rows(model, spec))
        alignment = ("---",) * len(spec.headers)
        empty = ("—",) * len(spec.headers)

    begin, end = MARKERS["markdown"]
    lines = [begin, f"<!-- {WRITTEN_BY} -->", ""]
    if spec.mirrors:
        lines.extend(
            [
                f"### {spec.heading}",
                "",
                f"The same view as `freeports-validate {spec.mirrors}`, "
                "for the whole repository at once.",
                "",
            ]
        )
    lines.extend(
        [
            _summary(model),
            "",
            f"*{NOTICE}* [{NOTICE_LINK_TEXT}]({GENERAL_METHODOLOGY_URL}).",
            "",
            "| " + " | ".join(spec.headers) + " |",
            "| " + " | ".join(alignment) + " |",
        ]
    )
    lines.extend("| " + " | ".join(row) + " |" for row in rows or [empty])
    for legend in _legends(model, spec) if spec.mirrors else []:
        lines.extend(["", legend])
    lines.extend(["", end, ""])
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# reStructuredText
# ---------------------------------------------------------------------------


def _rst_cell(model, dimension, value, mark=""):
    """No link here, deliberately.

    A methodology's URI would have to be an inline target, and a simple table whose cells carry
    inline targets is unreadable as text -- which is the only reason anyone writes reStructuredText
    by hand. The URIs are listed under the table instead, once each.
    """
    if dimension == "file":
        return f"``{value}``{mark}"
    return f"{value}{mark}"


def _rst_summary_rows(model):
    for methodology in model["methodologies"]:
        yield (
            methodology["name"],
            str(methodology["grants"]),
            _coverage_text(methodology["coverage"]),
            ", ".join(sorted({a["contributor"] for a in methodology["adoptions"]})),
        )


def _rst_pair_rows(model, table):
    for group, listed, states, mark in _pairs(model, table):
        yield (
            _rst_cell(model, table.group, group),
            _rst_cell(model, table.listed, listed, mark),
            states,
        )


def _rst_table(headers, rows):
    """A simple table: the rules are as wide as the widest cell in each column."""
    widths = [
        max(len(header), *(len(row[index]) for row in rows))
        for index, header in enumerate(headers)
    ]
    rule = "  ".join("=" * width for width in widths)

    def line(cells):
        return "  ".join(
            cell.ljust(width) for cell, width in zip(cells, widths)
        ).rstrip()

    return [rule, line(headers), rule, *(line(row) for row in rows), rule, ""]


def render_rst(model, table=DEFAULT_TABLE):
    spec = TABLES[table]
    if table == DEFAULT_TABLE:
        rows = list(_rst_summary_rows(model))
    else:
        rows = list(_rst_pair_rows(model, spec))
    rows = rows or [("—",) * len(spec.headers)]

    begin, end = MARKERS["rst"]
    lines = [begin, f".. {WRITTEN_BY}", ""]
    if spec.mirrors:
        lines.extend(
            [
                f"**{spec.heading}**",
                "",
                f"The same view as ``freeports-validate {spec.mirrors}``, "
                "for the whole repository at once.",
                "",
            ]
        )
    lines.extend(
        [
            _summary(model),
            "",
            f"*{NOTICE}*",
            f"`{NOTICE_LINK_TEXT} <{GENERAL_METHODOLOGY_URL}>`_.",
            "",
        ]
    )
    lines.extend(_rst_table(spec.headers, rows))
    for legend in _legends(model, spec) if spec.mirrors else []:
        lines.extend([legend, ""])

    # The methodologies and where each resolved from, under every table rather than only under the
    # summary: a reader looking at a name in any of the six is asking the same question about it.
    for methodology in model["methodologies"]:
        if methodology["uri"]:
            lines.append(f"* {methodology['name']}: {methodology['uri']}")
    lines.extend(["", end, ""])
    return "\n".join(lines)


def rewrite(text, block):
    """``text`` with everything between the markers replaced by ``block``.

    The markers are found in ``block`` itself rather than passed separately, so a block can only
    ever be written into a file marked for that same format. Idempotent by construction: what is
    written between the markers includes them, and what is replaced is everything from one to the
    other.
    """
    begin, end = next(
        (pair for pair in MARKERS.values() if block.startswith(pair[0])), (None, None)
    )
    if begin is None:
        raise ValueError("the block carries no markers")

    start = text.find(begin)
    stop = text.find(end, start + len(begin)) if start != -1 else -1
    if start == -1 or stop == -1:
        raise MarkersMissing(
            f"the file carries no {begin} … {end} pair. "
            "Paste both lines where the table should go, and run this again."
        )
    return text[:start] + block.rstrip("\n") + text[stop + len(end) :]


# ---------------------------------------------------------------------------
# The command line
# ---------------------------------------------------------------------------

RENDERERS = {
    "json": render_json,
    "html": render_html,
    "markdown": render_markdown,
    "rst": render_rst,
}


def render(model, style, table=DEFAULT_TABLE):
    """One rendering of the model, as text. ``badges`` is not here: it is several files.

    `table` chooses among the seven arrangements of the repository, and only the two text formats
    have it. `json` is the model and a table of it would be a second, lossy one; `html` already
    carries the three viewpoints as tabs, so asking it for one of them would be asking for a page
    with two of its tabs removed. Both refuse rather than ignore the argument -- silently rendering
    something other than what was asked for is how a hook writes the wrong file for a year.
    """
    if style not in RENDERERS:
        raise KeyError(style)
    if table not in TABLES:
        raise KeyError(table)
    if style not in MARKERS:
        if table != DEFAULT_TABLE:
            raise KeyError(
                f"{style} has no tables; --table is for {', '.join(MARKERS)}"
            )
        return RENDERERS[style](model)
    return RENDERERS[style](model, table)


def _write_badges(model, directory):
    os.makedirs(directory, exist_ok=True)
    for name, content in render_badges(model).items():
        with open(os.path.join(directory, name), "w", encoding="utf-8") as handle:
            handle.write(content)


USAGE = f"Usage: report.py <{'|'.join(FORMATS)}> [--table NAME] [--out PATH]"


def main(argv):
    if not argv:
        print(USAGE, file=sys.stderr)
        return 2
    style, arguments = argv[0], argv[1:]
    if style not in FORMATS:
        print(f"Unknown format: {style}", file=sys.stderr)
        print(f"Formats: {', '.join(FORMATS)}", file=sys.stderr)
        return 2

    out = None
    table = DEFAULT_TABLE
    while arguments:
        if arguments[0] == "--out" and len(arguments) > 1:
            out = arguments[1]
            arguments = arguments[2:]
            continue
        if arguments[0] == "--table" and len(arguments) > 1:
            table = arguments[1]
            arguments = arguments[2:]
            continue
        print(f"Unexpected argument: {arguments[0]}", file=sys.stderr)
        print(USAGE, file=sys.stderr)
        return 2

    if table not in TABLES:
        print(f"Unknown table: {table}", file=sys.stderr)
        print(f"Tables: {', '.join(TABLES)}", file=sys.stderr)
        return 2

    model = json.load(sys.stdin)

    if style == "badges":
        if out is None:
            print(
                "badges are several files, so --out must name a directory to put them in",
                file=sys.stderr,
            )
            return 2
        _write_badges(model, out)
        return 0

    try:
        text = render(model, style, table)
    except KeyError as refused:
        print(refused.args[0], file=sys.stderr)
        return 2

    # Markdown and reStructuredText are rewritten *into* a file rather than over it: the table is
    # part of a README somebody wrote, and the rest of that README is theirs.
    if style in MARKERS and out is not None:
        with open(out, encoding="utf-8") as handle:
            existing = handle.read()
        try:
            updated = rewrite(existing, text)
        except MarkersMissing as missing:
            print(f"{out}: {missing}", file=sys.stderr)
            return 1
        with open(out, "w", encoding="utf-8") as handle:
            handle.write(updated)
        return 0

    if out is None:
        sys.stdout.write(text)
        return 0

    with open(out, "w", encoding="utf-8") as handle:
        handle.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
