//! The Python shims of the domain vocabularies: currency, SFDR article, financial instrument.
//!
//! The native types are plain Rust enums, deliberately not annotated for Python — the shim layer
//! does not touch existing code — so three newtypes wrap them here and expose the protocol a
//! formats repository's author code already uses: a variant as a class attribute, its name and
//! value, equality and hashing.
//!
//! The class constants are generated by a macro from the list of variants the native type already
//! exposes: writing them out would have meant forty-six declarations for the currencies alone.

use pyo3::prelude::*;
use pyo3::types::PyType;

use crate::commons::consts::{Currency, FinancialInstrument, SfdrArticle};

/// Generates the Python newtype of a field-less enum: construction by name, the name and value
/// attributes, equality, hashing, representation, indexing by name, and the members map — that is,
/// the part of the enumeration protocol existing code uses.
macro_rules! enum_shim {
    ($shim:ident, $native:ty, $py_name:literal, $variants:expr, $name_of:expr) => {
        #[doc = concat!("Shim Python di [`", stringify!($native), "`].")]
        #[pyclass(name = $py_name, module = "freeports.consts", frozen, eq, hash)]
        #[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
        pub struct $shim($native);

        impl From<$native> for $shim {
            fn from(value: $native) -> Self {
                $shim(value)
            }
        }

        impl $shim {
            /// The wrapped native value — the only way the rest of the layer reads it.
            pub fn inner(&self) -> $native {
                self.0
            }

            /// The variant's name, which is also the key Python addresses it by.
            fn variant_name(value: $native) -> &'static str {
                #[allow(clippy::redundant_closure_call)]
                ($name_of)(value)
            }

            /// The public name of the wrapped variant.
            pub fn variant_name_of(&self) -> &'static str {
                Self::variant_name(self.0)
            }

            fn by_name(name: &str) -> Option<$shim> {
                $variants.iter().copied().find(|v| Self::variant_name(*v) == name).map($shim)
            }
        }

        #[pymethods]
        impl $shim {
            #[getter]
            fn name(&self) -> &'static str {
                Self::variant_name(self.0)
            }

            /// The value is the name itself: these enumerations are string-valued, and formats
            /// repositories read one or the other indifferently.
            #[getter]
            fn value(&self) -> &'static str {
                Self::variant_name(self.0)
            }

            fn __repr__(&self) -> String {
                format!("{}.{}", $py_name, Self::variant_name(self.0))
            }

            fn __str__(&self) -> String {
                self.__repr__()
            }

            /// Indexing by name.
            #[classmethod]
            fn __class_getitem__(_cls: &Bound<'_, PyType>, name: &str) -> PyResult<$shim> {
                Self::by_name(name).ok_or_else(|| {
                    // Past this point the lookup failure only lives as a Python `KeyError`,
                    // invisible to this crate's own tracing/CSV pipeline (same rationale as
                    // `python/input.rs`'s boundary functions).
                    tracing::error!(shim = $py_name, name, "unknown enum variant name");
                    pyo3::exceptions::PyKeyError::new_err(format!("{}: {name}", $py_name))
                })
            }

            #[classattr]
            fn __members__() -> std::collections::BTreeMap<&'static str, $shim> {
                $variants.iter().copied().map(|v| (Self::variant_name(v), $shim(v))).collect()
            }
        }
    };
}

/// The three SFDR variants, in the native type's declaration order.
const SFDR_VARIANTS: [SfdrArticle; 3] = [SfdrArticle::Art6, SfdrArticle::Art8, SfdrArticle::Art9];
/// The two instrument variants, in the native type's declaration order.
const INSTRUMENT_VARIANTS: [FinancialInstrument; 2] =
    [FinancialInstrument::EQUITY, FinancialInstrument::BOND];

enum_shim!(PyCurrency, Currency, "Currency", Currency::variants(), |v: Currency| v.code());
// The names visible from Python are the underscored ones, not the Rust identifiers: they are what
// author code writes and what already-recorded fixtures name the variant by. The crate's own naming
// convention is a separate matter from the public name.
enum_shim!(PySfdrArticle, SfdrArticle, "SfdrArticle", SFDR_VARIANTS, |v: SfdrArticle| match v {
    SfdrArticle::Art6 => "ART_6",
    SfdrArticle::Art8 => "ART_8",
    SfdrArticle::Art9 => "ART_9",
});
enum_shim!(
    PyFinancialInstrument,
    FinancialInstrument,
    "FinancialInstrument",
    INSTRUMENT_VARIANTS,
    |v: FinancialInstrument| match v {
        FinancialInstrument::EQUITY => "EQUITY",
        FinancialInstrument::BOND => "BOND",
    }
);

/// Adds an enumeration's class constants to a shim module.
///
/// Not declarative attributes, because those cannot be generated in variable number: they are
/// registered on the type after the module is built, which is the only point at which the Python
/// type object really exists.
fn attach_variants<T>(module: &Bound<'_, PyModule>, py_name: &str, values: Vec<(&str, T)>) -> PyResult<()>
where
    T: for<'py> IntoPyObject<'py>,
{
    let class = module.getattr(py_name)?;
    for (name, value) in values {
        class.setattr(name, value)?;
    }
    Ok(())
}

/// Registers the class constants of the three enumerations, right after the module is built.
pub fn init(module: &Bound<'_, PyModule>) -> PyResult<()> {
    attach_variants(
        module,
        "Currency",
        Currency::variants().iter().map(|v| (v.code(), PyCurrency::from(*v))).collect(),
    )?;
    attach_variants(
        module,
        "SfdrArticle",
        SFDR_VARIANTS.iter().map(|v| (PySfdrArticle::variant_name(*v), PySfdrArticle::from(*v))).collect(),
    )?;
    attach_variants(
        module,
        "FinancialInstrument",
        INSTRUMENT_VARIANTS
            .iter()
            .map(|v| (PyFinancialInstrument::variant_name(*v), PyFinancialInstrument::from(*v)))
            .collect(),
    )?;
    Ok(())
}
