#!/bin/bash
REPO_ROOT=$(git rev-parse --show-toplevel)
source "${REPO_ROOT}/validation/lib/utils"

VERSION=$(get_version_methodology)
if [ -f "${PERSONAL_DOC}" ]; then
    echo "File \"${PERSONAL_DOC}\" already present, refuse to overwrite" 1>&2
    echo "Delete the file before creating a new one" 1>&2
    exit 1
fi

concrete_yaml(){
    yq \
    ".version=\"${VERSION}\" | .who.name=\"${NAME}\" | .who.email=\"${EMAIL}\" | .who.pubkey_id=\"${KEYID}\"" \
    "${LIB_DIR}/document.template.yaml" -y
}


if (concrete_yaml | check-jsonschema --schemafile "${LIB_DIR}/document.schema.json" --default-filetype yaml - 1> /dev/null); then
    concrete_yaml > "${PERSONAL_DOC}"
fi
 