"""The gate: which commits go through, which are refused, and which are only reported.

`freeports-dev ci-check` is the one place in this workspace that stops a commit. It measures
nothing itself — it reads what the measurement commands left in `reports/`, the minima in
`ci.yaml`, and the class of the branch. That separation is what makes a threshold survivable: when
a commit is refused, the number that refused it is in a file, written by a command the person can
re-run by hand.

Every cell of the matrix below is a test here, **including the ones that must not refuse** — those
are the ones a change would silently break, because nobody notices a gate that stopped being strict
until the day it should have stopped something.

    verdict          dev       prod
    pass             —         —
    below            notify    refuse
    unmeasured       notify    refuse
    stale            notify    refuse
    no threshold     listed    listed

The two that are easy to get wrong:

**`unmeasured` is never a pass.** A figure nobody could compute is not a figure above the
threshold. Reporting it as one is exactly the failure this project already ruled out for a
methodology page it could not reach — unverifiable is not granted, and neither is unmeasured.

**`stale` is what makes the fast/slow split honest.** The hook measures the fast metrics at every
commit and reads the slow ones from the last `make ci`. Without staleness, a figure from three
weeks ago would gate today's commit and the split would quietly become a way of never measuring
the slow half at all.

One rule is *not* here and its absence is deliberate: grant integrity never refuses, on any branch.
A granted reference output regenerated by `make-tests` is ordinary work, and a contributor who does
not hold the granting key could not clear such a gate at all.
"""

import json
import subprocess
from argparse import Namespace

import pytest

from freeports_dev.ci import gate as ci_gate
from freeports_dev.ci import report
from freeports_dev.ci import suites as ci_suites
from freeports_dev.ci.config import CiConfig


def args(**overrides):
    return Namespace(
        **{
            "repo": None,
            "branch_class": None,
            "min": None,
            "keyserver": None,
            **overrides,
        }
    )


@pytest.fixture(autouse=True)
def no_ambient_environment(monkeypatch):
    import os

    for name in list(os.environ):
        if name.startswith("FREEPORTS_CI_") or name == "FREEPORTS_VALIDATE_KEYSERVER":
            monkeypatch.delenv(name, raising=False)


@pytest.fixture
def engine(tmp_path):
    """An engine-shaped repository on a `dev` branch, with a `main` available to switch to."""
    (tmp_path / "packages" / "freeports").mkdir(parents=True)
    subprocess.run(["git", "-C", str(tmp_path), "init", "-q", "-b", "dev"], check=True)
    return tmp_path


def configure(root, text):
    (root / "ci.yaml").write_text(text)
    return root


def measured(metric, value, head=None, unit="percent"):
    return report.Measurement(metric, value, unit, head=head)


def all_suites_ran(head=None):
    """Every suite this workspace knows, recorded as having passed at `head`.

    The default for the tests below that are about *metrics*. A gate lists every suite whether or
    not anybody ran one, so without this a test asking "does a figure at its minimum refuse on
    prod" would be answered by six suites nobody ran — which is a true answer to a different
    question. Suites get their own tests, further down, where the setup says so out loud.
    """
    return {
        suite.name: report.SuiteOutcome(suite.name, ci_suites.PASSED, head=head)
        for suite in ci_suites.REGISTRY
    }


def judge(
    root,
    thresholds,
    measurements,
    branch_class=None,
    head=None,
    conditions=None,
    suite_outcomes=None,
    reported_suites=None,
):
    configure(root, thresholds)
    config = CiConfig(root, args(branch_class=branch_class))
    return ci_gate.evaluate(
        config,
        measurements,
        conditions,
        head=head,
        suite_outcomes=all_suites_ran(head)
        if suite_outcomes is None
        else suite_outcomes,
        reported_suites=reported_suites,
    )


def condition_for(gate, suite):
    return next(c for c in gate.conditions if c.name == suite)


def verdict_for(gate, metric):
    return next(v for v in gate.verdicts if v.metric == metric)


class TestAFigureThatClearsItsMinimum:
    def test_it_passes(self, engine):
        gate = judge(
            engine,
            "thresholds:\n  docs.rust: 39\n",
            {"docs.rust": measured("docs.rust", 39.4)},
        )
        assert verdict_for(gate, "docs.rust").state == ci_gate.PASS

    def test_exactly_at_the_minimum_is_at_or_above_it(self, engine):
        """`>=`, not `>`. A threshold seeded at today's figure must not refuse today's commit."""
        gate = judge(
            engine,
            "thresholds:\n  docs.rust: 39.4\n",
            {"docs.rust": measured("docs.rust", 39.4)},
        )
        assert verdict_for(gate, "docs.rust").state == ci_gate.PASS

    def test_and_nothing_is_refused_even_on_prod(self, engine):
        gate = judge(
            engine,
            "thresholds:\n  docs.rust: 39\n",
            {"docs.rust": measured("docs.rust", 39.4)},
            branch_class="prod",
        )
        assert not gate.refuses
        assert gate.exit_status == 0


class TestAFigureUnderItsMinimum:
    def setup_gate(self, engine, branch_class):
        return judge(
            engine,
            "thresholds:\n  docs.rust: 40\n",
            {"docs.rust": measured("docs.rust", 39.4)},
            branch_class=branch_class,
        )

    def test_the_verdict_is_below(self, engine):
        assert (
            verdict_for(self.setup_gate(engine, "dev"), "docs.rust").state
            == ci_gate.BELOW
        )

    def test_on_dev_it_is_reported_and_the_commit_stands(self, engine):
        gate = self.setup_gate(engine, "dev")
        assert gate.failures and not gate.refuses
        assert gate.exit_status == 0

    def test_on_prod_it_refuses(self, engine):
        gate = self.setup_gate(engine, "prod")
        assert gate.refuses
        assert gate.exit_status == 1

    def test_the_reason_names_both_numbers(self, engine):
        reason = verdict_for(self.setup_gate(engine, "dev"), "docs.rust").reason
        assert "39.40" in reason and "40" in reason


class TestAFigureNobodyCouldCompute:
    """Never a pass. A figure nobody could compute is not a figure above the threshold."""

    def test_a_metric_with_a_minimum_and_no_measurement_at_all(self, engine):
        gate = judge(engine, "thresholds:\n  docs.rust: 39\n", {})
        assert verdict_for(gate, "docs.rust").state == ci_gate.UNMEASURED

    def test_a_measurement_that_says_it_failed(self, engine):
        unmeasured = report.Measurement.unmeasured(
            "tests.rust.lines", "cargo-llvm-cov is not installed."
        )
        gate = judge(
            engine,
            "thresholds:\n  tests.rust.lines: 50\n",
            {"tests.rust.lines": unmeasured},
        )
        assert verdict_for(gate, "tests.rust.lines").state == ci_gate.UNMEASURED

    def test_the_reason_the_tool_gave_is_the_reason_shown(self, engine):
        unmeasured = report.Measurement.unmeasured(
            "tests.rust.lines", "cargo-llvm-cov is not installed."
        )
        gate = judge(
            engine,
            "thresholds:\n  tests.rust.lines: 50\n",
            {"tests.rust.lines": unmeasured},
        )
        assert "cargo-llvm-cov" in verdict_for(gate, "tests.rust.lines").reason

    def test_it_is_reported_on_dev(self, engine):
        gate = judge(engine, "thresholds:\n  docs.rust: 39\n", {}, branch_class="dev")
        assert gate.failures and not gate.refuses

    def test_and_it_refuses_on_prod(self, engine):
        gate = judge(engine, "thresholds:\n  docs.rust: 39\n", {}, branch_class="prod")
        assert gate.refuses

    def test_a_value_of_zero_is_a_measurement_and_not_an_absence(self, engine):
        """Zero is a real figure. Confusing it with "unmeasured" would flatter a broken measurement."""
        gate = judge(
            engine,
            "thresholds:\n  docs.rust: 39\n",
            {"docs.rust": measured("docs.rust", 0.0)},
        )
        assert verdict_for(gate, "docs.rust").state == ci_gate.BELOW


class TestAFigureTakenAtAnotherCommit:
    """What makes the fast/slow split honest rather than a way of never measuring the slow half."""

    def test_a_measurement_from_another_commit_is_stale(self, engine):
        gate = judge(
            engine,
            "thresholds:\n  tests.rust.lines: 50\n",
            {"tests.rust.lines": measured("tests.rust.lines", 91.2, head="old")},
            head="new",
        )
        assert verdict_for(gate, "tests.rust.lines").state == ci_gate.STALE

    def test_even_when_it_clears_the_minimum_easily(self, engine):
        gate = judge(
            engine,
            "thresholds:\n  tests.rust.lines: 50\n",
            {"tests.rust.lines": measured("tests.rust.lines", 99.9, head="old")},
            head="new",
        )
        assert verdict_for(gate, "tests.rust.lines").state != ci_gate.PASS

    def test_the_message_names_the_command_that_fixes_it(self, engine):
        gate = judge(
            engine,
            "thresholds:\n  tests.rust.lines: 50\n",
            {"tests.rust.lines": measured("tests.rust.lines", 91.2, head="oldcommit")},
            head="newcommit",
        )
        assert "make ci" in verdict_for(gate, "tests.rust.lines").reason

    def test_one_taken_at_this_commit_is_current(self, engine):
        gate = judge(
            engine,
            "thresholds:\n  tests.rust.lines: 50\n",
            {"tests.rust.lines": measured("tests.rust.lines", 91.2, head="same")},
            head="same",
        )
        assert verdict_for(gate, "tests.rust.lines").state == ci_gate.PASS

    def test_a_repository_with_no_commit_cannot_have_a_stale_figure(self, engine):
        """Guessing here would refuse commits in a repository nobody has ever committed to."""
        gate = judge(
            engine,
            "thresholds:\n  tests.rust.lines: 50\n",
            {"tests.rust.lines": measured("tests.rust.lines", 91.2, head="anything")},
            head=None,
        )
        assert verdict_for(gate, "tests.rust.lines").state == ci_gate.PASS

    def test_a_measurement_recording_no_commit_is_judged_on_its_value(self, engine):
        gate = judge(
            engine,
            "thresholds:\n  tests.rust.lines: 50\n",
            {"tests.rust.lines": measured("tests.rust.lines", 91.2, head=None)},
            head="new",
        )
        assert verdict_for(gate, "tests.rust.lines").state == ci_gate.PASS

    def test_it_is_reported_on_dev_and_refuses_on_prod(self, engine):
        stale = {"tests.rust.lines": measured("tests.rust.lines", 91.2, head="old")}
        on_dev = judge(
            engine, "thresholds:\n  tests.rust.lines: 50\n", stale, "dev", head="new"
        )
        on_prod = judge(
            engine, "thresholds:\n  tests.rust.lines: 50\n", stale, "prod", head="new"
        )
        assert on_dev.failures and not on_dev.refuses
        assert on_prod.refuses


class TestAMetricNobodyConfigured:
    def test_it_is_listed_and_gates_nothing(self, engine):
        gate = judge(engine, "", {"docs.rust": measured("docs.rust", 39.4)})
        assert verdict_for(gate, "docs.rust").state == ci_gate.NO_THRESHOLD

    def test_not_even_when_it_could_not_be_measured(self, engine):
        """Being able to see an unconfigured figure is how a threshold gets seeded at a real one."""
        gate = judge(engine, "", {}, branch_class="prod")
        assert not gate.refuses
        assert gate.exit_status == 0

    def test_every_metric_the_repository_can_answer_for_is_listed(self, engine):
        gate = judge(engine, "", {})
        listed = {v.metric for v in gate.verdicts}
        assert "tests.rust.lines" in listed and "grants.coverage" in listed

    def test_and_the_ones_it_cannot_are_not(self, tmp_path):
        (tmp_path / "metadata").mkdir()
        (tmp_path / "metadata" / "formats.csv").write_text("Name,Locale,Year\n")
        subprocess.run(
            ["git", "-C", str(tmp_path), "init", "-q", "-b", "main"], check=True
        )
        gate = judge(tmp_path, "", {})
        listed = {v.metric for v in gate.verdicts}
        assert "tests.formats.integration" in listed
        assert "tests.rust.lines" not in listed


class TestPerPackageMinima:
    """The most specific name wins; the aggregate covers whatever no specific name claims."""

    def test_a_package_is_judged_against_its_own_minimum(self, engine):
        gate = judge(
            engine,
            "thresholds:\n  tests.python.lines: 60\n  tests.python.freeports_validate.lines: 40\n",
            {
                "tests.python.lines": measured("tests.python.lines", 65.0),
                "tests.python.freeports_validate.lines": measured(
                    "tests.python.freeports_validate.lines", 45.0
                ),
            },
        )
        assert (
            verdict_for(gate, "tests.python.freeports_validate.lines").state
            == ci_gate.PASS
        )

    def test_a_package_below_its_own_minimum_fails_even_when_the_aggregate_passes(
        self, engine
    ):
        gate = judge(
            engine,
            "thresholds:\n  tests.python.lines: 30\n  tests.python.freeports_validate.lines: 90\n",
            {
                "tests.python.lines": measured("tests.python.lines", 65.0),
                "tests.python.freeports_validate.lines": measured(
                    "tests.python.freeports_validate.lines", 45.0
                ),
            },
            branch_class="prod",
        )
        assert gate.refuses

    def test_the_aggregate_says_which_packages_were_taken_out_of_it(self, engine):
        gate = judge(
            engine,
            "thresholds:\n  tests.python.lines: 30\n  tests.python.freeports_validate.lines: 40\n",
            {
                "tests.python.lines": measured("tests.python.lines", 65.0),
                "tests.python.freeports_validate.lines": measured(
                    "tests.python.freeports_validate.lines", 45.0
                ),
            },
        )
        assert "freeports_validate" in verdict_for(gate, "tests.python.lines").reason


class TestReadingASuiteOutcomeOffACommandLine:
    def test_a_suite_that_passed_is_read_as_passed(self):
        assert ci_gate.parse_suite("rust.unit:passed") == (
            "rust.unit",
            ci_suites.PASSED,
        )

    def test_a_suite_that_failed_is_not(self):
        assert ci_gate.parse_suite("rust.unit:failed") == (
            "rust.unit",
            ci_suites.FAILED,
        )

    def test_a_word_nobody_intended_is_read_as_failure_not_success(self):
        """A hook writes this from a shell variable. The one way it must not fail is as a yes."""
        assert ci_gate.parse_suite("rust.unit:probably")[1] == ci_suites.FAILED
        assert ci_gate.parse_suite("rust.unit:")[1] == ci_suites.FAILED

    def test_an_empty_variable_is_a_failure_and_not_a_pass(self):
        """The shape a hook produces when the command it meant to run was never started."""
        assert ci_gate.parse_suite("rust.unit: ")[1] == ci_suites.FAILED


class TestASuiteThatRanHere:
    def test_it_is_listed_as_having_run(self, engine):
        gate = judge(engine, "", {})
        assert condition_for(gate, "rust.unit").state == ci_gate.RAN

    def test_and_nothing_is_refused_even_on_prod(self, engine):
        gate = judge(engine, "", {}, "prod")
        assert not gate.refuses

    def test_what_the_caller_reports_now_outranks_what_is_on_disk(self, engine):
        """A run in progress is more current than a run recorded at some earlier commit."""
        gate = judge(
            engine,
            "",
            {},
            suite_outcomes={
                "rust.unit": report.SuiteOutcome(
                    "rust.unit", ci_suites.PASSED, head="0" * 40
                )
            },
            reported_suites={"rust.unit": ci_suites.FAILED},
            head="1" * 40,
        )
        assert condition_for(gate, "rust.unit").state == ci_gate.BROKE


class TestASuiteThatBroke:
    def setup_gate(self, engine, branch_class):
        outcomes = all_suites_ran()
        outcomes["rust.unit"] = report.SuiteOutcome("rust.unit", ci_suites.FAILED)
        return judge(engine, "", {}, branch_class, suite_outcomes=outcomes)

    def test_the_verdict_says_it_broke(self, engine):
        assert (
            condition_for(self.setup_gate(engine, "dev"), "rust.unit").state
            == ci_gate.BROKE
        )

    def test_it_refuses_on_prod(self, engine):
        assert self.setup_gate(engine, "prod").refuses

    def test_and_is_only_reported_on_dev(self, engine):
        gate = self.setup_gate(engine, "dev")
        assert gate.failures and not gate.refuses

    def test_the_detail_names_the_command_that_runs_it(self, engine):
        detail = condition_for(self.setup_gate(engine, "dev"), "rust.unit").detail
        assert "make test-rust-unit" in detail


class TestASuiteNobodyRanHere:
    """Not run is never a pass, for the reason `unmeasured` is never one.

    This is the verdict the whole fast/slow split rests on. A gate that runs the two cheap suites
    and prints nothing about the four it skipped is a gate that reports "tests: ok" on the strength
    of a third of them — which is worse than reporting nothing, because a reader believes it.
    """

    def test_every_suite_this_repository_has_is_listed_even_with_no_reports_at_all(
        self, engine
    ):
        gate = judge(engine, "", {}, suite_outcomes={})
        listed = {c.name for c in gate.conditions}
        assert {"rust.unit", "rust.integration", "rust.doc", "python.fast"} <= listed

    def test_the_verdict_is_not_run(self, engine):
        gate = judge(engine, "", {}, suite_outcomes={})
        assert condition_for(gate, "rust.integration").state == ci_gate.NOT_RUN

    def test_it_refuses_on_prod(self, engine):
        """Nothing may be stale on a production branch, and never-run is the limit case of stale."""
        assert judge(engine, "", {}, "prod", suite_outcomes={}).refuses

    def test_and_is_only_reported_on_dev(self, engine):
        gate = judge(engine, "", {}, "dev", suite_outcomes={})
        assert gate.failures and not gate.refuses

    def test_the_detail_says_why_it_is_not_in_the_commit_gate(self, engine):
        gate = judge(engine, "", {}, suite_outcomes={})
        assert (
            "costs more than seconds" in condition_for(gate, "rust.integration").detail
        )

    def test_and_an_online_one_says_it_is_the_network_rather_than_the_clock(
        self, engine
    ):
        """Two categories, one policy: the message keeps them apart, the gate treats them alike."""
        gate = judge(engine, "", {}, suite_outcomes={})
        assert "needs the network" in condition_for(gate, "python.online").detail

    def test_a_formats_repository_is_never_asked_about_the_crate(self, tmp_path):
        (tmp_path / "content").mkdir()
        (tmp_path / "metadata").mkdir()
        (tmp_path / "metadata" / "formats.csv").write_text("format\n")
        (tmp_path / "package.yaml").write_text("info:\n  version: 0.0.1\n")
        subprocess.run(
            ["git", "-C", str(tmp_path), "init", "-q", "-b", "dev"], check=True
        )
        gate = judge(tmp_path, "", {}, suite_outcomes={})
        listed = {c.name for c in gate.conditions}
        assert "formats.single_page" in listed
        assert not any(name.startswith("rust.") for name in listed)


class TestASuiteThatRanAtAnotherCommit:
    """Stale is what makes running a subset honest rather than merely convenient."""

    def setup_gate(self, engine, branch_class):
        outcomes = all_suites_ran(head="a" * 40)
        return judge(
            engine, "", {}, branch_class, head="b" * 40, suite_outcomes=outcomes
        )

    def test_the_verdict_is_stale(self, engine):
        assert (
            condition_for(self.setup_gate(engine, "dev"), "rust.doc").state
            == ci_gate.SUITE_STALE
        )

    def test_the_detail_names_both_commits(self, engine):
        detail = condition_for(self.setup_gate(engine, "dev"), "rust.doc").detail
        assert "aaaaaaaa" in detail and "bbbbbbbb" in detail

    def test_it_refuses_on_prod(self, engine):
        assert self.setup_gate(engine, "prod").refuses

    def test_and_is_only_reported_on_dev(self, engine):
        gate = self.setup_gate(engine, "dev")
        assert gate.failures and not gate.refuses

    def test_a_repository_with_no_commit_cannot_have_a_stale_suite(self, engine):
        """Guessing here would refuse every commit in a repository that has never had one."""
        gate = judge(
            engine,
            "",
            {},
            "prod",
            head=None,
            suite_outcomes=all_suites_ran(head="a" * 40),
        )
        assert condition_for(gate, "rust.doc").state == ci_gate.RAN


class TestASuiteNobodyHasHeardOf:
    """Listed rather than dropped: a suite that ran and was silently not counted is the one
    outcome this table exists to prevent."""

    def test_it_is_still_listed(self, engine):
        gate = judge(engine, "", {}, reported_suites={"house.style": ci_suites.PASSED})
        assert condition_for(gate, "house.style").state == ci_gate.RAN

    def test_and_a_failing_one_still_refuses_on_prod(self, engine):
        gate = judge(
            engine, "", {}, "prod", reported_suites={"house.style": ci_suites.FAILED}
        )
        assert gate.refuses


class TestTheConditionsThatAreNotSuites:
    def test_a_condition_that_does_not_apply_here_fails_nothing(self, engine):
        condition = ci_gate.Condition("fingerprint vs version", False, applicable=False)
        gate = judge(engine, "", {}, "prod", conditions=[condition])
        assert not gate.refuses


class TestTheBranchClassDecidesAndNothingElse:
    def test_off_refuses_nothing_however_bad_the_figures(self, engine):
        gate = judge(
            engine,
            "thresholds:\n  docs.rust: 90\n",
            {"docs.rust": measured("docs.rust", 1.0)},
            branch_class="off",
        )
        assert gate.failures and not gate.refuses

    def test_dev_refuses_nothing_either(self, engine):
        gate = judge(
            engine,
            "thresholds:\n  docs.rust: 90\n",
            {"docs.rust": measured("docs.rust", 1.0)},
            branch_class="dev",
        )
        assert not gate.refuses

    def test_only_prod_refuses(self, engine):
        gate = judge(
            engine,
            "thresholds:\n  docs.rust: 90\n",
            {"docs.rust": measured("docs.rust", 1.0)},
            branch_class="prod",
        )
        assert gate.refuses

    def test_a_prod_branch_with_nothing_wrong_passes(self, engine):
        gate = judge(
            engine,
            "thresholds:\n  docs.rust: 39\n",
            {"docs.rust": measured("docs.rust", 39.4)},
            branch_class="prod",
        )
        assert gate.exit_status == 0


class TestTheRenderings:
    def gate_with_a_problem(self, engine):
        return judge(
            engine,
            "thresholds:\n  docs.rust: 40\n  lint.rust: 9.9\n",
            {
                "docs.rust": measured("docs.rust", 39.4),
                "lint.rust": measured("lint.rust", 9.998, unit="score"),
            },
        )

    def test_the_table_says_which_branch_and_which_rule_put_it_there(self, engine):
        rendered = ci_gate.render_text(self.gate_with_a_problem(engine))
        assert "branch dev -> dev" in rendered
        assert "reported, not enforced" in rendered

    def test_a_failing_line_gets_a_sentence_not_just_a_verdict(self, engine):
        rendered = ci_gate.render_text(self.gate_with_a_problem(engine))
        assert "docs.rust — " in rendered

    def test_a_score_is_printed_at_the_precision_it_is_judged_at(self, engine):
        """Two decimals round 9.998 to "10.00" and then call it under a minimum of 10."""
        rendered = ci_gate.render_text(self.gate_with_a_problem(engine))
        assert "9.998" in rendered

    def test_a_dev_branch_says_what_would_have_happened_on_prod(self, engine):
        rendered = ci_gate.render_text(self.gate_with_a_problem(engine))
        assert "On a prod branch" in rendered

    def test_the_json_carries_the_exit_status_it_chose(self, engine):
        rendered = json.loads(ci_gate.render_json(self.gate_with_a_problem(engine)))
        assert rendered["exit_status"] == 0
        assert rendered["refused"] is False
        assert rendered["class"] == "dev"

    def test_the_json_lists_every_metric_with_its_verdict(self, engine):
        rendered = json.loads(ci_gate.render_json(self.gate_with_a_problem(engine)))
        by_metric = {m["metric"]: m for m in rendered["metrics"]}
        assert by_metric["docs.rust"]["verdict"] == ci_gate.BELOW
        assert by_metric["lint.rust"]["verdict"] == ci_gate.PASS

    def test_skipping_the_slow_metrics_is_said_out_loud(self, engine):
        configure(engine, "")
        config = CiConfig(engine, args())
        gate = ci_gate.evaluate(config, {}, skipped_slow=["tests.rust.lines"])
        rendered = ci_gate.render_text(gate)
        assert "tests.rust.lines" in rendered
        assert "not checked at all" in rendered
